import { defineConfig } from 'vitest/config';

/** Blocking structural coverage for new reusable D&D 2024 state primitives. */
export default defineConfig({
  test: {
    environment: 'node',
    maxWorkers: 4,
    testTimeout: 30_000,
    hookTimeout: 60_000,
    include: [
      'src/rules-core/actorTraits.test.ts',
      'src/rules-core/armorOfAgathys.test.ts',
      'src/rules-core/attackSequence.test.ts',
      'src/rules-core/dwarfTraits.test.ts',
      'src/rules-core/familiarActorCatalog.test.ts',
      'src/rules-core/familiarRuntime.test.ts',
      'src/rules-core/fightingStyles.test.ts',
      'src/rules-core/findFamiliar.test.ts',
      'src/rules-core/systemActions.test.ts',
      'src/rules-core/microMvpSpellScope.test.ts',
      'src/rules-core/pactBladeRuntime.test.ts',
      'src/rules-core/pactBladeWorldAdapter.test.ts',
      'src/rules-core/pactTomeRuntime.test.ts',
      'src/rules-core/pactTomeWorldAdapter.test.ts',
      'src/rules-core/protection.test.ts',
      'src/rules-core/spellcastingAccess.test.ts',
      'src/rules-core/warlockPacts.test.ts',
      'src/rules-core/worldObjects.test.ts',
      'src/rules-core/worldSpellPrimitives.test.ts',
    ],
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      reportsDirectory: 'coverage/rules-primitives',
      include: [
        'src/rules-core/actorTraits.ts',
        'src/rules-core/armorOfAgathys.ts',
        'src/rules-core/attackSequence.ts',
        'src/rules-core/dwarfTraits.ts',
        'src/rules-core/familiarActorCatalog.ts',
        'src/rules-core/familiarRuntime.ts',
        'src/rules-core/fightingStyles.ts',
        'src/rules-core/findFamiliar.ts',
        'src/rules-core/systemActions.ts',
        'src/rules-core/microMvpSpellScope.ts',
        'src/rules-core/pactBladeRuntime.ts',
        'src/rules-core/pactBladeWorldAdapter.ts',
        'src/rules-core/pactTomeRuntime.ts',
        'src/rules-core/pactTomeWorldAdapter.ts',
        'src/rules-core/protection.ts',
        'src/rules-core/spellcastingAccess.ts',
        'src/rules-core/warlockPacts.ts',
        'src/rules-core/worldObjects.ts',
        'src/rules-core/worldSpellPrimitives.ts',
      ],
      thresholds: {
        statements: 100,
        branches: 100,
        functions: 100,
        lines: 100,
      },
    },
  },
});
