version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: dnd_cards_db
    environment:
      POSTGRES_DB: dnd_cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - dnd_cards_network

  # Backend API (Golang)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dnd_cards_backend
    environment:
      DATABASE_URL: host=postgres user=postgres password=postgres dbname=dnd_cards port=5432 sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - dnd_cards_network
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dnd_cards_frontend
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dnd_cards_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  dnd_cards_network:
    driver: bridge

