import{test}from'node:test';import assert from'node:assert/strict';
import{pair}from'./writer-policy-unit-fixture.mjs';import{evidenceHash}from'./validate-manifest.mjs';import{hostedWriterProvenance,cleanupWriterBrowserCase}from'./produce-writer-browser-proof.mjs';
function fixture(){const {candidate:manifest}=pair();return {candidate:{manifest,provenance:{schemaVersion:1,releaseRunId:9,controlCommit:'c'.repeat(40),sourceCommit:manifest.releaseCommit,planHash:'sha256:'+'d'.repeat(64),manifestHash:evidenceHash(manifest)}},environment:{GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:'owner/project',GITHUB_REF:'refs/heads/main',GITHUB_WORKFLOW_REF:'owner/project/.github/workflows/release.yml@refs/heads/main',GITHUB_SHA:'c'.repeat(40),GITHUB_RUN_ID:'9',GITHUB_RUN_ATTEMPT:'2'}};}
test('producer binds actual running main control attempt without pretending workflow success',()=>{const f=fixture(),p=hostedWriterProvenance(f.candidate,f.environment);assert.equal(p.runAttempt,2);assert.equal(p.releaseRunId,9);assert.ok(!('conclusion'in p));assert.ok(!('verifiedReleaseRun'in p));});
test('wrong fork/workflow/source/control/attempt cannot produce a publishable fixture',()=>{
 for(const change of [f=>f.candidate.frontendVerification={},f=>f.environment.GITHUB_ACTIONS='false',f=>f.environment.GITHUB_REF='refs/pull/1/merge',f=>f.environment.GITHUB_WORKFLOW_REF='fork/project/.github/workflows/release.yml@refs/heads/main',f=>f.environment.GITHUB_RUN_ID='10',f=>f.environment.GITHUB_RUN_ATTEMPT='0',f=>f.environment.GITHUB_SHA='d'.repeat(40),f=>f.candidate.provenance.manifestHash='sha256:'+'0'.repeat(64),f=>f.candidate.provenance.sourceCommit='f'.repeat(40)]){const f=fixture();change(f);assert.throws(()=>hostedWriterProvenance(f.candidate,f.environment));}
});

test('failed executable rehash cannot suppress either independent owned cleanup',async()=>{const calls=[];await assert.rejects(cleanupWriterBrowserCase({assertUnchanged:async()=>{calls.push('hash');throw Error('changed');},cleanup:async()=>{calls.push('browser');throw Error('browser cleanup');}},{cleanup:async()=>{calls.push('apps');return{status:'stopped'};}}),error=>error instanceof AggregateError&&error.errors.length===2);assert.deepEqual(calls,['hash','browser','apps']);});
