import test from 'node:test';import assert from 'node:assert/strict';import {discoverPublishedCandidate} from './release-publication.mjs';
function fixture(){const repository='unit/project',now=Date.parse('2026-10-05T02:00:00Z');
 const run={id:70,run_attempt:2,path:'.github/workflows/release.yml',head_sha:'a'.repeat(40),head_branch:'main',event:'workflow_run',status:'completed',conclusion:'success',repository:{full_name:repository},head_repository:{full_name:repository}};
 const job={id:71,run_id:70,run_attempt:2,name:'publish',head_sha:run.head_sha,status:'completed',conclusion:'success',started_at:'2026-10-05T01:00:00Z',completed_at:'2026-10-05T01:20:00Z'};
 const artifact={id:72,name:'release-candidate',expired:false,size_in_bytes:100,created_at:'2026-10-05T01:19:00Z',expires_at:'2026-11-05T00:00:00Z',workflow_run:{id:70,head_sha:run.head_sha}};
 const calls=[];let reads=0;const get=async route=>{calls.push(route);if(route==='actions/runs/70'){reads++;return structuredClone(run);}if(route.startsWith('actions/runs/70/jobs?'))return {total_count:1,jobs:[structuredClone(job)]};if(route.startsWith('actions/runs/70/artifacts?'))return {total_count:1,artifacts:[structuredClone(artifact)]};throw Error('Unexpected route');};
 return {repository,now,run,job,artifact,calls,get,reads:()=>reads};}
test('published candidate is bound to exact latest run attempt and artifact ID',async()=>{const f=fixture(),r=await discoverPublishedCandidate(f.get,{...f,runId:70});assert.equal(r.available,true);assert.equal(r.artifactId,72);assert.equal(r.run.runAttempt,2);assert.equal(f.reads(),2);});
test('canonical no-publication path never reads old candidates or advances deployment baseline',async()=>{const f=fixture();f.job.conclusion='skipped';const r=await discoverPublishedCandidate(f.get,{...f,runId:70});assert.equal(r.available,false);for(const key of ['createCandidate','deploy','advanceBaseline'])assert.equal(r[key],false);assert.equal(r.artifactId,null);assert.ok(!f.calls.some(x=>x.includes('/artifacts')));});
for(const [name,mutate]of [['stale attempt',f=>f.job.run_attempt=1],['wrong control',f=>f.job.head_sha='b'.repeat(40)],['old artifact',f=>f.artifact.created_at='2026-10-04T01:00:00Z'],['expired',f=>f.artifact.expired=true],['failed publish',f=>f.job.conclusion='failure'],['other artifact run',f=>f.artifact.workflow_run.id=69]])test(`publication rejects ${name}`,async()=>{const f=fixture();mutate(f);await assert.rejects(discoverPublishedCandidate(f.get,{...f,runId:70}));});
test('rerun during discovery fails closed',async()=>{const f=fixture(),get=async route=>{const r=await f.get(route);if(route==='actions/runs/70'&&f.reads()===2)r.run_attempt=3;return r;};await assert.rejects(discoverPublishedCandidate(get,{...f,runId:70}),/changed/);});
test('normalized invalid calendar dates cannot authorize an artifact attempt',async()=>{const f=fixture();f.job.started_at='2026-02-30T01:00:00Z';await assert.rejects(discoverPublishedCandidate(f.get,{...f,runId:70}),/dates/);});
