// Synthetic orchestration fault tests, never OCI evidence.
import {test} from 'node:test';import assert from 'node:assert/strict';
import {probeWriterPolicySequence} from './writer-policy-sequence.mjs';import {pair} from './writer-policy-unit-fixture.mjs';import {writerTraceBinding} from './writer-traces.mjs';
function fixture(){
 const f=pair(),binding=writerTraceBinding(f.candidate,f.check,f.bundle.rehearsalReceipt),records=new Map(),sequence=[];let running=false,role,policy,worker=0,provider=0;
 const adapter={execution:'docker',assertOwned:async()=>{},start:async options=>{assert.equal(running,false);running=true;role=options.role;policy={compactReceipts:options.compactReceipts,imageJobs:options.imageJobs,frozenCatalogs:options.frozenCatalogs};sequence.push(role);},stopApplications:async()=>{running=false;},observe:async()=>({...binding[role],environment:[`DB_COMPACT_RECEIPTS=${+policy.compactReceipts}`,`IMAGE_JOBS_ENABLED=${+policy.imageJobs}`,'DB_FROZEN_CATALOGS=0']}),workerCalls:async()=>worker,imageStats:async()=>({unexpected:0,providerCalls:provider,storageUploads:provider?1:0})};
 const compactIO={fixtures:async()=>['roguelike_command_receipts','character_runtime_commands'].map((table,i)=>({table,commandId:String(i)})),request:async value=>{const prior=records.get(value.table);if(prior)return {status:200,body:{...prior,...(value.table==='character_runtime_commands'?{replayed:true}:{})}};worker++;const body={result:'accepted',...(value.table==='character_runtime_commands'?{replayed:false}:{})};records.set(value.table,body);return {status:200,body};},readReceipt:async value=>({response_version:2,body:records.get(value.table)}),invariant:async()=>({worker,resource:10-worker})};
 const jobsIO={createSettledCases:async()=>{provider=2;return ['succeeded','unknown'].map((id,i)=>({id,jobId:String(i)}));},read:async row=>({status:200,body:{job:{id:row.jobId,state:row.id}}}),retry:async row=>({status:202,body:{job:{id:row.jobId,state:row.id}}}),readOtherOwner:async()=>({status:404})};
 return {binding,adapter,compactIO,jobsIO,sequence,get stopped(){return !running;},charge:()=>provider++};
}
test('real-role orchestration requires ON to previous OFF to ON without replay charges',async()=>{const f=fixture(),trace=await probeWriterPolicySequence(f);assert.deepEqual(f.sequence,['candidate','previous','candidate']);assert.equal(f.stopped,true);assert.equal(trace.observations.length,3);assert.equal(new Set(trace.observations.map(r=>r.receiptResponseHash)).size,1);assert.equal(new Set(trace.observations.map(r=>r.jobIdentityHash)).size,1);});
test('provider redispatch or substituted previous image refuses and stops processes',async()=>{
 for(const mode of ['provider','image']){const f=fixture();if(mode==='provider'){const original=f.jobsIO.retry;f.jobsIO.retry=async row=>{const r=await original(row);f.charge();return r;};}else{const original=f.adapter.observe;f.adapter.observe=async()=>{const r=await original();return f.sequence.at(-1)==='previous'?{...r,images:{...r.images,backend:'foreign'}}:r;};}await assert.rejects(probeWriterPolicySequence(f));assert.equal(f.stopped,true);}
});
