import {loadHistoricalCatalogSources} from '../historical-catalog-source.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {sha256Canonical} from '../../../scripts/content/certification-hash.mjs';
const hash=b=>'sha256:'+createHash('sha256').update(b).digest('hex');
const literal=s=>"'"+s.replaceAll("'","''")+"'";
async function source(){
 const publicPackage=await loadHistoricalCatalogSources(),entities=publicPackage.caster296.rows,manifestBytes=await fs.readFile('backend/migrations/spell_grant_abilities_296_manifest.json');assert.equal(hash(manifestBytes),'sha256:310047ba934a9fed8bba48476eee4491670be698fe07bf9391762664d7580add');const manifest=JSON.parse(manifestBytes),proof={sourceDumpHash:entities[0].sourceDumpHash,sourceBoundary:'297_retain_generic_spell_free_uses'};assert.equal(entities.length,42);assert.equal(entities.length,manifest.evidence.length);
 for(const e of entities){assert(['classes','effects'].includes(e.table));const guard=manifest.evidence.find(g=>g.table===e.table&&g.id===e.id);assert(guard);assert.equal(e.sourceDumpHash,proof.sourceDumpHash);assert.deepEqual(e.fields,guard.fields);assert.equal(sha256Canonical(e.fields),guard.expected_hash);assert.equal(e.sourceProjectionHash,guard.expected_hash);assert.equal(e.fields.id,e.id);assert.equal(e.fields.card_number,e.reference);}
 assert.equal(new Set(entities.map(e=>e.table+':'+e.id)).size,entities.length);return {proof,entities,fixtureHash:publicPackage.manifest.datasets.caster296.jsonSha256};
}
async function inspect(query,entities){
 assert.equal((await query('fresh_chain','SELECT max(version) FROM schema_migrations;')).trim(),'295_stable_spell_grant_references');
 const rows=[];
 for(const e of entities){const fields=Object.keys(e.fields);assert(fields.every(k=>/^[a-z][a-z0-9_]*$/.test(k)));const value=JSON.parse(await query('fresh_chain',"SET LOCAL TIME ZONE 'UTC';SELECT coalesce(json_agg(jsonb_build_object('id',id,'reference',card_number,'active',deleted_at IS NULL,'rowHash','sha256:'||encode(sha256(convert_to(to_jsonb(t)::text,'UTF8')),'hex'),'fields',(SELECT jsonb_object_agg(key,value) FROM jsonb_each(to_jsonb(t)) WHERE key IN("+fields.map(literal).join(',')+")),'remainingHash','sha256:'||encode(sha256(convert_to((to_jsonb(t)-ARRAY["+fields.map(literal).join(',')+",'updated_at'])::text,'UTF8')),'hex'))),'[]'::json) FROM "+e.table+" t WHERE id="+literal(e.id)+'::uuid OR card_number='+literal(e.reference)+';'));
 assert.equal(value.length,1,'Caster source requires exact existing identity');const actual=value[0];assert.equal(actual.id,e.id);assert.equal(actual.reference,e.reference);assert.equal(actual.active,true);
 const differentFields=fields.filter(k=>!isDeepStrictEqual(actual.fields[k],e.fields[k]));rows.push({...e,...actual,differentFields,exact:sha256Canonical(actual.fields)===e.sourceProjectionHash});}
 return rows;
}

async function referenceProjection(query, selected, expected){
 const pieces=selected.map(r=>{const kind=r.table==='classes'?'class':'effect';const fields=JSON.stringify(Object.fromEntries(r.differentFields.map(k=>[k,r.sourceFields[k]])));return expected?"SELECT "+literal(kind)+" AS source_type,"+literal(r.id)+" AS source_id,refs.* FROM "+r.table+" t CROSS JOIN LATERAL entity_reference_extract("+literal(kind)+",to_jsonb(t)||"+literal(fields)+"::jsonb) refs WHERE t.id="+literal(r.id)+"::uuid":"SELECT source_type,source_id,target_type,target_key,level,path FROM entity_reference_edges WHERE source_type="+literal(kind)+" AND source_id="+literal(r.id);});
 return JSON.parse(await query('fresh_chain',"SELECT coalesce(json_agg(to_jsonb(p) ORDER BY source_type,source_id,target_type,target_key,level,path),'[]'::json) FROM ("+pieces.join(' UNION ALL ')+") p;"));
}
async function preservedSnapshot(query, exclusions, selected){
 const tables=JSON.parse(await query('fresh_chain',"SELECT json_agg(c.relname ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','m');"));assert(Array.isArray(tables));assert(tables.every(t=>/^[a-z_][a-z0-9_]*$/.test(t)));assert(tables.includes('entity_reference_edges'));
 const pieces=tables.map(table=>{const excluded=exclusions.find(e=>e.table===table);let predicate=excluded?'id NOT IN('+excluded.ids.map(id=>literal(id)+'::uuid').join(',')+')':'';if(table==='entity_reference_edges')predicate='NOT('+selected.map(r=>'(source_type='+literal(r.table==='classes'?'class':'effect')+' AND source_id='+literal(r.id)+')').join(' OR ')+')';return "SELECT "+literal(table)+" AS table_name,count(*) AS rows,encode(sha256(convert_to(coalesce(string_agg(h,E'\\n' ORDER BY h),''),'UTF8')),'hex') AS hash FROM (SELECT encode(sha256(convert_to(to_jsonb(t)::text,'UTF8')),'hex') h FROM public."+table+" t "+(predicate?'WHERE '+predicate:'')+") values_by_row";});
 return JSON.parse(await query('fresh_chain',"SELECT json_agg(row_to_json(t) ORDER BY table_name) FROM ("+pieces.join(' UNION ALL ')+") t;"));
}

export async function hydrateAuthenticCaster296({query,fullDataSnapshot,observe=()=>{}}){
 const {proof,entities,fixtureHash}=await source(),before=await inspect(query,entities);observe({stage:'actual295-caster-source-preconditions',targets:before.length,passed:before.filter(r=>r.exact).length,failed:before.filter(r=>!r.exact).length,drift:before.filter(r=>!r.exact).map(r=>({table:r.table,reference:r.reference,differentFields:r.differentFields}))});
 const selected=before.filter(r=>!r.exact).map(r=>({...r,sourceFields:entities.find(e=>e.table===r.table&&e.id===r.id).fields}));if(!selected.length)return {kind:'authentic-caster296-source-already-exact',targets:42,passed:42,updated:0,productionChanges:0};
 const forbidden=['id','card_number','support','author','user_id','group_id','created_at','updated_at','deleted_at'];for(const r of selected)assert(r.differentFields.every(k=>!forbidden.includes(k)));
 const exclusions=[...new Set(selected.map(r=>r.table))].map(table=>({table,ids:selected.filter(r=>r.table===table).map(r=>r.id)}));const rawNonTargetBefore=await fullDataSnapshot(exclusions),nonTargetBefore=await preservedSnapshot(query,exclusions,selected),expectedReferenceProjection=await referenceProjection(query,selected,true),referenceBefore=await referenceProjection(query,selected,false),ledgerBefore=await query('fresh_chain',"SELECT encode(sha256(convert_to(coalesce(string_agg(to_jsonb(t)::text,E'\\n' ORDER BY version),''),'UTF8')),'hex') FROM schema_migrations t;");
 const statements=["BEGIN;SET LOCAL TIME ZONE 'UTC';SET LOCAL statement_timeout='60s';LOCK TABLE "+exclusions.map(e=>e.table).join(',')+' IN SHARE ROW EXCLUSIVE MODE;'];
 for(const r of selected){const fields=r.differentFields,value=Object.fromEntries(fields.map(k=>[k,entities.find(e=>e.table===r.table&&e.id===r.id).fields[k]]));statements.push('DO $caster$ DECLARE n integer;BEGIN UPDATE '+r.table+' t SET('+fields.join(',')+')=(SELECT '+fields.join(',')+' FROM jsonb_populate_record(NULL::'+r.table+','+literal(JSON.stringify(value))+'::jsonb)) WHERE id='+literal(r.id)+'::uuid AND encode(sha256(convert_to(to_jsonb(t)::text,\'UTF8\')),\'hex\')='+literal(r.rowHash.slice(7))+';GET DIAGNOSTICS n=ROW_COUNT;IF n<>1 THEN RAISE EXCEPTION \'Caster source target changed\';END IF;END $caster$;');}
 statements.push('COMMIT;');await query('fresh_chain',statements.join('\n'),{readOnly:false});
 const after=await inspect(query,entities),rawNonTargetAfter=await fullDataSnapshot(exclusions),nonTargetAfter=await preservedSnapshot(query,exclusions,selected),referenceAfter=await referenceProjection(query,selected,false),ledgerAfter=await query('fresh_chain',"SELECT encode(sha256(convert_to(coalesce(string_agg(to_jsonb(t)::text,E'\\n' ORDER BY version),''),'UTF8')),'hex') FROM schema_migrations t;");assert(after.every(r=>r.exact));assert.deepEqual(referenceAfter,expectedReferenceProjection);assert.deepEqual(nonTargetAfter,nonTargetBefore);assert.equal(ledgerAfter,ledgerBefore);for(const r of before)assert.equal(after.find(a=>a.table===r.table&&a.id===r.id).remainingHash,r.remainingHash);
 return {schemaVersion:1,kind:'authentic-public-source-caster-evidence-at295',fixtureHash,sourceDumpHash:proof.sourceDumpHash,sourceBoundary:proof.sourceBoundary,originalFullSnapshot:false,before:{targets:42,passed:42-selected.length,failed:selected.length},after:{targets:42,passed:42,failed:0},updated:selected.length,changedFields:selected.map(r=>({table:r.table,id:r.id,reference:r.reference,fields:r.differentFields})),nonTargetBefore,nonTargetAfter,rawNonTargetBefore,rawNonTargetAfter,referenceBefore,referenceAfter,expectedReferenceProjection,referenceProjectionMatchesOriginalExtractor:true,allUnrelatedReferenceRowsExact:true,ledgerBefore,ledgerAfter,allExistingHistoryAndOtherNonDerivedRowsExact:true,allOtherTargetFieldsExact:true,allOriginalLedgerRowsExact:true,manualStatusesAssignedByHydration:false,originalManifestChanged:false,productionChanges:0};
}
