package migrations

import (
	"database/sql"
	"fmt"
)

const levelTwoClassFeaturesMigrationVersion = "154_materialize_level_two_class_features"

type levelTwoActionSeed struct {
	id, card, name, nameEn, description, resource, mechanics string
}

var levelTwoActions = []levelTwoActionSeed{
	{"15400000-0000-4000-8000-000000000001", "ACT-reckless-attack", "Безрассудная атака", "Reckless Attack", "До следующего хода атаки Силой получают преимущество, а атаки по вам — преимущество.", "free_action", `{"activation":{"mode":"active","cost":[]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"advantage","stack_id":"reckless:self-attacks","applies_to":{"roll":"attack","filter":{"ability":"str"}},"duration":{"type":"until_start_of_next_turn"}},{"kind":"modifier","op":"advantage","stack_id":"reckless:attacks-against-self","scope":"target","applies_to":{"roll":"attack"},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000002", "ACT-channel-divinity-divine-spark-heal", "Божественная искра: исцеление", "Divine Spark: Heal", "Исцеляет выбранное существо на 1к8 + модификатор Мудрости.", "action", `{"activation":{"mode":"active","cost":[{"resource":"action"},{"resource":"channel_divinity"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"single","min_targets":1,"max_targets":1,"range_ft":30,"requires_line_of_sight":true,"allowed_relations":["self","ally","neutral"]},"effects":[{"resolution":"auto","who":"target","result":[{"kind":"healing","amount":"1d8 + wis"}]}]}`},
	{"15400000-0000-4000-8000-000000000003", "ACT-channel-divinity-divine-spark-radiant", "Божественная искра: урон излучением", "Divine Spark: Radiant", "Цель совершает спасбросок Телосложения; при провале получает 1к8 + Мудрость урона излучением, при успехе — половину.", "action", `{"activation":{"mode":"active","cost":[{"resource":"action"},{"resource":"channel_divinity"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"single","min_targets":1,"max_targets":1,"range_ft":30,"requires_line_of_sight":true,"allowed_relations":["enemy","neutral"]},"effects":[{"resolution":"save","ability":"con","dc":"spell_save_dc","on_fail":[{"kind":"damage","amount":"1d8 + wis","type":"radiant"}],"on_success":[{"kind":"damage","amount":"floor((1d8 + wis)/2)","type":"radiant"}]}]}`},
	{"15400000-0000-4000-8000-000000000004", "ACT-channel-divinity-turn-undead", "Изгнание нежити", "Turn Undead", "Нежить в пределах 30 футов совершает спасбросок Мудрости; при провале Испугана и Недееспособна до 1 минуты.", "action", `{"activation":{"mode":"active","cost":[{"resource":"action"},{"resource":"channel_divinity"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"area","min_targets":1,"max_targets":20,"range_ft":0,"allowed_relations":["enemy","neutral"],"area":{"kind":"sphere","radius_ft":30},"filter":{"creature_type":"undead"}},"effects":[{"resolution":"save","ability":"wis","dc":"spell_save_dc","on_fail":[{"kind":"grant_effect","value":"COND-frightened","duration":{"type":"minutes","amount":1}},{"kind":"grant_effect","value":"COND-incapacitated","duration":{"type":"minutes","amount":1}}]}]}`},
	{"15400000-0000-4000-8000-000000000005", "ACT-wild-companion", "Дикий спутник", "Wild Companion", "Расходует Дикий облик и сотворяет Обретение фамильяра без материального компонента; фамильяр — Фея до долгого отдыха.", "action", `{"activation":{"mode":"active","cost":[{"resource":"action"},{"resource":"wild_shape"}]},"targeting":{"domain":"world","actor_targets":false,"shape":"point","range_ft":10},"effects":[{"resolution":"auto","result":[{"kind":"world_entity","entity":"fey_familiar","duration":{"type":"until_long_rest"}},{"kind":"narrative","description":"Разместите фамильяра-Фею в выбранной точке; он исчезает после долгого отдыха."}]}]}`},
	{"15400000-0000-4000-8000-000000000006", "ACT-monk-flurry-of-blows", "Шквал ударов", "Flurry of Blows", "Тратит 1 очко Фокуса: два безоружных удара бонусным действием.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"},{"resource":"focus"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"single","min_targets":1,"max_targets":1,"range_ft":5,"allowed_relations":["enemy","neutral"]},"effects":[{"resolution":"attack_roll","attack_kind":"unarmed","ability":"dex","vs":"ac","on_hit":[{"kind":"damage","amount":"1d6 + dex","type":"bludgeoning"}]},{"resolution":"attack_roll","attack_kind":"unarmed","ability":"dex","vs":"ac","on_hit":[{"kind":"damage","amount":"1d6 + dex","type":"bludgeoning"}]}]}`},
	{"15400000-0000-4000-8000-000000000007", "ACT-monk-patient-defense", "Терпеливая оборона", "Patient Defense", "Бонусным действием совершает Отход.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"deny","applies_to":{"interaction":"opportunity_attack","trigger":"self_movement"},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000008", "ACT-monk-patient-defense-focus", "Терпеливая оборона: Фокус", "Patient Defense: Focus", "Тратит 1 Фокус: Отход и Уклонение бонусным действием.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"},{"resource":"focus"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"deny","applies_to":{"interaction":"opportunity_attack","trigger":"self_movement"},"duration":{"type":"until_start_of_next_turn"}},{"kind":"modifier","op":"disadvantage","scope":"target","applies_to":{"roll":"attack"},"duration":{"type":"until_start_of_next_turn"}},{"kind":"modifier","op":"advantage","applies_to":{"roll":"saving_throw","filter":{"ability":"dex"}},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000009", "ACT-monk-step-of-the-wind", "Шаг ветра", "Step of the Wind", "Бонусным действием совершает Рывок.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"multiply","value":2,"applies_to":{"roll":"speed"},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000010", "ACT-monk-step-of-the-wind-focus", "Шаг ветра", "Step of the Wind: Focus", "Тратит 1 Фокус: Рывок и Отход; дистанция прыжка удваивается на ход.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"},{"resource":"focus"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"multiply","value":2,"applies_to":{"roll":"speed"},"duration":{"type":"until_start_of_next_turn"}},{"kind":"modifier","op":"deny","applies_to":{"interaction":"opportunity_attack","trigger":"self_movement"},"duration":{"type":"until_start_of_next_turn"}},{"kind":"modifier","op":"multiply","value":2,"applies_to":{"roll":"jump_distance"},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000011", "ACT-monk-uncanny-metabolism", "Необычный метаболизм", "Uncanny Metabolism", "После броска инициативы восстанавливает весь Фокус и 1к6 + уровень монаха хитов; один раз за долгий отдых.", "free_action", `{"activation":{"mode":"active","cost":[{"resource":"self_uses"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"resource","op":"restore","id":"focus","amount":"class_level:monk"},{"kind":"healing","amount":"1d6 + class_level:monk"}]}],"uses":{"count":1,"per":"long_rest"}}`},
	{"15400000-0000-4000-8000-000000000012", "ACT-cunning-dash", "Хитрое действие: Рывок", "Cunning Action: Dash", "Совершает Рывок бонусным действием.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"multiply","value":2,"applies_to":{"roll":"speed"},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000013", "ACT-cunning-disengage", "Хитрое действие: Отход", "Cunning Action: Disengage", "Совершает Отход бонусным действием.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"deny","applies_to":{"interaction":"opportunity_attack","trigger":"self_movement"},"duration":{"type":"until_start_of_next_turn"}}]}]}`},
	{"15400000-0000-4000-8000-000000000014", "ACT-cunning-hide", "Хитрое действие: Засада", "Cunning Action: Hide", "Проверка Ловкости (Скрытность) Сл 15 бонусным действием; при успехе даёт состояние Невидимый.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"ability_check","ability":"dex","skill":"stealth","dc":15,"on_success":[{"kind":"grant_effect","value":"COND-invisible","duration":{"type":"manual"}}]}]}`},
	{"15400000-0000-4000-8000-000000000015", "ACT-font-create-slot-1", "Создать ячейку 1 круга", "Create Level 1 Spell Slot", "Тратит 2 очка чародейства и восстанавливает ячейку 1 круга.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"},{"resource":"sorcery_points","amount":2}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"resource","op":"restore","id":"spell_slot_1","amount":1}]}]}`},
	{"15400000-0000-4000-8000-000000000016", "ACT-font-convert-slot-1", "Преобразовать ячейку 1 круга", "Convert Level 1 Spell Slot", "Тратит ячейку 1 круга и восстанавливает 1 очко чародейства.", "bonus_action", `{"activation":{"mode":"active","cost":[{"resource":"bonus_action"},{"resource":"spell_slot_1"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"resource","op":"restore","id":"sorcery_points","amount":1}]}]}`},
	{"15400000-0000-4000-8000-000000000017", "ACT-magical-cunning", "Магическая хитрость", "Magical Cunning", "Минутный ритуал восстанавливает одну потраченную ячейку Магии договора; один раз за долгий отдых.", "free_action", `{"activation":{"mode":"active","cost":[{"resource":"self_uses"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"resource","op":"restore","id":"pact_slot_1","amount":1}]}],"uses":{"count":1,"per":"long_rest"}}`},
	{"15400000-0000-4000-8000-000000000018", "ACT-tactical-mind", "Тактический ум", "Tactical Mind", "После проваленной проверки тратит использование Второго дыхания и даёт к10 к этой проверке; расход возвращается, если проверка всё равно провалена.", "free_action", `{"activation":{"mode":"active","cost":[{"resource":"uses_ACT-second-wind"}]},"targeting":{"domain":"actor","actor_targets":true,"shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"grant_effect","value":"EFFECT-tactical-mind-die"}]}]}`},
	{"15400000-0000-4000-8000-000000000019", "ACT-wild-companion-slot", "Дикий спутник: ячейка", "Wild Companion: Spell Slot", "Расходует ячейку 1 круга и сотворяет Обретение фамильяра без материального компонента; фамильяр — Фея до долгого отдыха.", "action", `{"activation":{"mode":"active","cost":[{"resource":"action"},{"resource":"spell_slot","level":1,"amount":1}]},"targeting":{"domain":"world","actor_targets":false,"shape":"point","range_ft":10},"effects":[{"resolution":"auto","result":[{"kind":"world_entity","entity":"fey_familiar","duration":{"type":"until_long_rest"}},{"kind":"narrative","description":"Разместите фамильяра-Фею в выбранной точке; он исчезает после долгого отдыха."}]}]}`},
}

func materializeLevelTwoClassFeatures(db *sql.DB) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err = tx.Exec(`DROP TRIGGER IF EXISTS protect_actions_certified_mechanics ON actions; DROP TRIGGER IF EXISTS protect_effects_certified_mechanics ON effects;`); err != nil {
		return err
	}
	for _, action := range levelTwoActions {
		if _, err = tx.Exec(`INSERT INTO actions (id,name,name_en,description,image_url,rarity,card_number,action_type,type,resource,mechanics,author,source,support)
		VALUES ($1::uuid,$2,$3,$4,'','common',$5,'class_feature','class_feature',$6,$7::jsonb,'System','PHB 2024',jsonb_build_object('status','untested','certification_version',$8::text,'mechanics_locked',false,'note','Level-2 browser verification pending'))
		ON CONFLICT (card_number) DO UPDATE SET deleted_at=NULL,name=EXCLUDED.name,name_en=EXCLUDED.name_en,description=EXCLUDED.description,resource=EXCLUDED.resource,mechanics=EXCLUDED.mechanics,support=EXCLUDED.support,updated_at=NOW()`, action.id, action.name, action.nameEn, action.description, action.card, action.resource, action.mechanics, levelTwoClassFeaturesMigrationVersion); err != nil {
			return fmt.Errorf("upsert %s: %w", action.card, err)
		}
	}
	updates := []struct{ card, description, mechanics string }{
		{"EFF-reckless-attack", "Перед первой атакой хода включите Безрассудную атаку: атаки Силой с преимуществом, но атаки по вам также с преимуществом до следующего хода.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","value":"ACT-reckless-attack"}]}]}`},
		{"EFF-danger-sense", "Преимущество на спасброски Ловкости, пока вы не Недееспособны.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"advantage","applies_to":{"roll":"saving_throw","filter":{"ability":"dex"}},"when":[{"kind":"not","of":{"kind":"you_have_condition","value":"incapacitated"}}]}]}]}`},
		{"EFF-jack-of-all-trades", "Добавляйте половину бонуса мастерства к проверкам навыков, где у вас нет владения.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"add","value":"floor(prof_bonus/2)","applies_to":{"roll":"ability_check","filter":{"proficient":false}}}]}]}`},
		{"EFF-channel-divinity", "Два использования Канала божественности: Божественная искра или Изгнание нежити. Одно использование возвращается после короткого отдыха, все — после долгого.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","values":["ACT-channel-divinity-divine-spark-heal","ACT-channel-divinity-divine-spark-radiant","ACT-channel-divinity-turn-undead"]}]}]}`},
		{"EFF-wild-companion", "Сотворите Обретение фамильяра без материального компонента, расходуя ячейку или Дикий облик; фамильяр — Фея и исчезает после долгого отдыха.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","values":["ACT-wild-companion","ACT-wild-companion-slot"]}]}]}`},
		{"EFF-unarmored-movement", "Скорость увеличивается на 10 футов, пока вы без доспеха и щита.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"modifier","op":"add","value":10,"applies_to":{"roll":"speed"},"when":[{"kind":"not","of":{"kind":"wearing_armor"}},{"kind":"not","of":{"kind":"wielding_shield"}}]}]}]}`},
		{"EFF-uncanny-metabolism", "После броска инициативы можно восстановить весь Фокус и 1к6 + уровень монаха хитов; один раз за долгий отдых.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","value":"ACT-monk-uncanny-metabolism"}]}]}`},
		{"EFF-monk-focus", "Очки Фокуса равны уровню монаха. Доступны Шквал ударов, Терпеливая оборона и Шаг ветра.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","values":["ACT-monk-flurry-of-blows","ACT-monk-patient-defense","ACT-monk-patient-defense-focus","ACT-monk-step-of-the-wind","ACT-monk-step-of-the-wind-focus"]}]}]}`},
		{"EFF-paladin-smite", "Божественная кара всегда подготовлена; одно сотворение после попадания бесплатно после каждого долгого отдыха.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_spell","value":"SPELL-0164","label":"prepared","freeuse":{"count":1,"per":"long_rest"}}]}]}`},
		{"EFF-deft-explorer", "Выберите один имеющийся навык для экспертизы и два языка.", `{"activation":{"mode":"passive"},"effects":[{"kind":"choice","id":"ranger_deft_explorer_expertise","prompt":"Ловкий исследователь: выберите навык с владением","count":1,"resolution":"on_acquire","options":{"source":"skill","filter":"proficient"},"grant":{"kind":"grant_proficiency","prof":"skill","expert":true}},{"kind":"choice","id":"ranger_deft_explorer_languages","prompt":"Ловкий исследователь: выберите 2 языка","count":2,"resolution":"on_acquire","options":{"source":"language"},"grant":{"kind":"grant_proficiency","prof":"language"}}]}`},
		{"EFF-cunning-action", "Рывок, Отход или Засада бонусным действием.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","values":["ACT-cunning-dash","ACT-cunning-disengage","ACT-cunning-hide"]}]}]}`},
		{"EFF-font-of-magic", "Два очка чародейства; преобразуйте ячейку 1 круга в 1 очко или 2 очка в ячейку 1 круга.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","values":["ACT-font-create-slot-1","ACT-font-convert-slot-1"]}]}]}`},
		{"EFF-tactical-mind", "После проваленной проверки характеристики потратьте Второе дыхание и добавьте 1к10. Если проверка всё ещё провалена, использование возвращается.", `{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","value":"ACT-tactical-mind"}]}]}`},
		{"EFF-wizard-scholar", "Выберите Аркану, Историю, Анализ, Медицину, Природу или Религию, которым уже владеете, и получите экспертизу.", `{"activation":{"mode":"passive"},"effects":[{"kind":"choice","id":"wizard_scholar_expertise","prompt":"Учёный: выберите навык с владением","count":1,"resolution":"on_acquire","options":{"source":"skill","filter":["arcana","history","investigation","medicine","nature","religion"]},"grant":{"kind":"grant_proficiency","prof":"skill","expert":true}}]}`},
	}
	for _, update := range updates {
		if _, err = tx.Exec(`UPDATE effects SET description=$2,mechanics=$3::jsonb,support=jsonb_build_object('status','untested','certification_version',$4::text,'mechanics_locked',false,'note','Level-2 browser verification pending'),updated_at=NOW() WHERE card_number=$1 AND deleted_at IS NULL`, update.card, update.description, update.mechanics, levelTwoClassFeaturesMigrationVersion); err != nil {
			return fmt.Errorf("update %s: %w", update.card, err)
		}
	}
	finishStatements := []struct {
		name        string
		query       string
		withVersion bool
	}{
		{"tactical mind boon", `INSERT INTO effects (id,name,name_en,description,detailed_description,image_url,rarity,card_number,effect_type,mechanics,repeatable,author,source,support)
		VALUES ('15400000-0000-4000-8000-000000000101','Тактический ум: кость','Tactical Mind Die','Добавьте 1к10 к проваленной проверке характеристики.','','','common','EFFECT-tactical-mind-die','positive_effect','{"kind":"boon","id":"tactical_mind","die":"1d10","applies_to":["ability_check"],"timing":["after_failure"],"consume":"on_roll","refund_on_failure":{"resource":"uses_ACT-second-wind","amount":1},"duration":{"type":"immediate"}}'::jsonb,false,'System','PHB 2024',jsonb_build_object('status','untested','certification_version',$1::text,'mechanics_locked',false,'note','Level-2 browser verification pending'))
		ON CONFLICT (card_number) DO UPDATE SET deleted_at=NULL,mechanics=EXCLUDED.mechanics,support=EXCLUDED.support,updated_at=NOW()`, true},
		{"magical cunning effect", `INSERT INTO effects (id,name,name_en,description,detailed_description,image_url,rarity,card_number,effect_type,mechanics,repeatable,author,source,support)
		VALUES ('15400000-0000-4000-8000-000000000102','Магическая хитрость','Magical Cunning','Минутный ритуал восстанавливает половину ячеек Магии договора (округляя вверх), один раз за долгий отдых.','','','common','EFF-magical-cunning','class_ability','{"activation":{"mode":"passive"},"effects":[{"resolution":"auto","result":[{"kind":"grant_action","value":"ACT-magical-cunning"}]}]}'::jsonb,false,'System','PHB 2024',jsonb_build_object('status','untested','certification_version',$1::text,'mechanics_locked',false,'note','Level-2 browser verification pending'))
		ON CONFLICT (card_number) DO UPDATE SET deleted_at=NULL,mechanics=EXCLUDED.mechanics,support=EXCLUDED.support,updated_at=NOW()`, true},
		{"warlock magical cunning effect progression", `UPDATE classes SET level_progression=jsonb_set(level_progression,'{2,effects}',COALESCE(level_progression#>'{2,effects}','[]'::jsonb)||jsonb_build_array('15400000-0000-4000-8000-000000000102'),true),updated_at=NOW() WHERE card_number='CLASS-warlock' AND NOT (COALESCE(level_progression#>'{2,effects}','[]'::jsonb) ? '15400000-0000-4000-8000-000000000102')`, false},
		{"warlock magical cunning action progression", `UPDATE classes SET level_progression=jsonb_set(level_progression,'{2,actions}',COALESCE(level_progression#>'{2,actions}','[]'::jsonb)||jsonb_build_array('15400000-0000-4000-8000-000000000017'),true),updated_at=NOW() WHERE card_number='CLASS-warlock' AND NOT (COALESCE(level_progression#>'{2,actions}','[]'::jsonb) ? '15400000-0000-4000-8000-000000000017')`, false},
		{"monk metabolism action progression", `UPDATE classes SET level_progression=jsonb_set(level_progression,'{2,actions}',COALESCE(level_progression#>'{2,actions}','[]'::jsonb)||jsonb_build_array('15400000-0000-4000-8000-000000000011'),true),updated_at=NOW() WHERE card_number='CLASS-monk' AND NOT (COALESCE(level_progression#>'{2,actions}','[]'::jsonb) ? '15400000-0000-4000-8000-000000000011')`, false},
		{"cleric channel divinity resource", `UPDATE classes SET resources=jsonb_set(COALESCE(resources,'{}'::jsonb),'{channel_divinity}','{"by_level":{"2":2},"per":"short_rest","recovery":{"short_rest":{"mode":"fixed","amount":1},"long_rest":{"mode":"full"}}}'::jsonb,true),updated_at=NOW() WHERE card_number='CLASS-cleric'`, false},
		{"druid wild shape resource", `UPDATE classes SET resources=jsonb_set(COALESCE(resources,'{}'::jsonb),'{wild_shape}','{"by_level":{"2":2},"per":"short_rest","recovery":{"short_rest":{"mode":"fixed","amount":1},"long_rest":{"mode":"full"}}}'::jsonb,true),updated_at=NOW() WHERE card_number='CLASS-druid'`, false},
		{"monk focus resource", `UPDATE classes SET resources=jsonb_set(COALESCE(resources,'{}'::jsonb),'{focus}','{"by_level":{"2":2},"per":"short_rest"}'::jsonb,true),updated_at=NOW() WHERE card_number='CLASS-monk'`, false},
		{"sorcerer points resource", `UPDATE classes SET resources=jsonb_set(COALESCE(resources,'{}'::jsonb),'{sorcery_points}','{"by_level":{"2":2},"per":"long_rest"}'::jsonb,true),updated_at=NOW() WHERE card_number='CLASS-sorcerer'`, false},
		{"sorcerer level-two spell choice count", `UPDATE effects SET mechanics=jsonb_set(mechanics,'{effects,0,result,0,count}','2'::jsonb,true),description='На 2 уровне выберите два дополнительных подготовленных заклинания чародея.',updated_at=NOW() WHERE card_number='caster-sorcerer-spells' AND deleted_at IS NULL`, false},
		{"remove ranger druidic warrior", `UPDATE classes SET level_progression=jsonb_set(level_progression,'{2,effects}',(COALESCE(level_progression#>'{2,effects}','[]'::jsonb) - COALESCE((SELECT id::text FROM effects WHERE card_number='EFF-druidic-warrior' AND deleted_at IS NULL LIMIT 1),'')),true),updated_at=NOW() WHERE card_number='CLASS-ranger'`, false},
		{"action surge contract", `UPDATE actions SET mechanics='{"activation":{"mode":"active","cost":[{"resource":"self_uses"}]},"targeting":{"domain":"actor","shape":"self","allowed_relations":["self"]},"effects":[{"resolution":"auto","result":[{"kind":"resource","op":"restore","id":"action","amount":1}]}],"uses":{"count":1,"per":"short_rest"}}'::jsonb,description='Получите ещё одно Действие в текущем ходу; один раз до короткого или долгого отдыха.',support=jsonb_build_object('status','untested','certification_version',$1::text,'mechanics_locked',false,'note','Level-2 browser verification pending'),updated_at=NOW() WHERE card_number='ACT-action-surge'`, true},
		{"wild shape contract", `UPDATE actions SET mechanics='{"activation":{"mode":"active","cost":[{"resource":"bonus_action"},{"resource":"wild_shape"}]},"targeting":{"domain":"actor","shape":"self","allowed_relations":["self"]},"effects":[{"kind":"choice","id":"wild_shape_form","prompt":"Выберите изученный облик зверя","count":1,"resolution":"on_use","options":{"source":"explicit","items":[{"id":"wolf","name":"Волк","grants":[{"kind":"transform","form":"Волк","max_cr":0.25,"temporary_hp":2}]},{"id":"panther","name":"Пантера","grants":[{"kind":"transform","form":"Пантера","max_cr":0.25,"temporary_hp":2}]},{"id":"spider","name":"Паук","grants":[{"kind":"transform","form":"Паук","max_cr":0,"temporary_hp":2}]},{"id":"draft_horse","name":"Тягловая лошадь","grants":[{"kind":"transform","form":"Тягловая лошадь","max_cr":0.25,"temporary_hp":2}]}]}}]}'::jsonb,description='Бонусным действием примите один из четырёх изученных обликов зверя с ПО не выше 1/4 и без скорости полёта. Получите 2 временных хита.',support=jsonb_build_object('status','untested','certification_version',$1::text,'mechanics_locked',false,'note','Level-2 browser verification pending'),updated_at=NOW() WHERE card_number='ACT-wild-shape'`, true},
		{"level-two actor targeting invariant", `UPDATE actions SET mechanics=jsonb_set(mechanics,'{targeting,actor_targets}',CASE WHEN mechanics#>>'{targeting,shape}'='self' THEN 'false'::jsonb ELSE 'true'::jsonb END,true),updated_at=NOW() WHERE (id::text LIKE '15400000-%' OR card_number IN ('ACT-action-surge','ACT-wild-shape')) AND mechanics#>>'{targeting,domain}'='actor'`, false},
		{"monk focus action label", `UPDATE actions SET name='Шаг ветра: Фокус',updated_at=NOW() WHERE card_number='ACT-monk-step-of-the-wind-focus'`, false},
		{"metamagic choices", `UPDATE effects SET description='Выберите 2 варианта Метамагии. Каждый вариант показывает стоимость и точный момент применения в карточке заклинания.',mechanics='{"activation":{"mode":"passive"},"effects":[{"kind":"choice","id":"sorcerer_metamagic","prompt":"Выберите 2 варианта Метамагии","count":2,"resolution":"on_acquire","options":{"source":"explicit","items":[{"id":"careful","name":"Осторожное","grants":[{"kind":"narrative","description":"1 ОЧ: до модификатора ХАР выбранных существ автоматически преуспевают в спасброске заклинания."}]},{"id":"distant","name":"Далёкое","grants":[{"kind":"narrative","description":"1 ОЧ: удвойте дальность заклинания не меньше 5 футов или сделайте касание дальностью 30 футов."}]},{"id":"empowered","name":"Усиленное","grants":[{"kind":"narrative","description":"1 ОЧ: перебросьте до модификатора ХАР костей урона; можно после других вариантов Метамагии."}]},{"id":"extended","name":"Продлённое","grants":[{"kind":"narrative","description":"1 ОЧ: удвойте длительность от 1 минуты (до 24 часов); преимущество на спасброски концентрации."}]},{"id":"heightened","name":"Непреодолимое","grants":[{"kind":"narrative","description":"2 ОЧ: одна цель получает помеху на спасброски против заклинания."}]},{"id":"quickened","name":"Ускоренное","grants":[{"kind":"narrative","description":"2 ОЧ: заклинание с Действием сотворяется Бонусным действием."}]},{"id":"seeking","name":"Ищущее","grants":[{"kind":"narrative","description":"1 ОЧ после промаха: перебросьте к20 атаки заклинанием."}]},{"id":"subtle","name":"Неуловимое","grants":[{"kind":"narrative","description":"1 ОЧ: сотворение без вербального, соматического и материального компонента без стоимости."}]},{"id":"transmuted","name":"Преобразованное","grants":[{"kind":"narrative","description":"1 ОЧ: замените кислоту, холод, огонь, молнию, яд или гром на другой тип из этого списка."}]},{"id":"twinned","name":"Удвоенное","grants":[{"kind":"narrative","description":"1 ОЧ: для подходящего заклинания увеличьте действующий круг на 1, чтобы выбрать дополнительную цель."}] }]}}]}'::jsonb,support=jsonb_build_object('status','untested','certification_version',$1::text,'mechanics_locked',false,'note','Level-2 browser verification pending'),updated_at=NOW() WHERE card_number='EFF-metamagic'`, true},
	}
	for _, statement := range finishStatements {
		if statement.withVersion {
			_, err = tx.Exec(statement.query, levelTwoClassFeaturesMigrationVersion)
		} else {
			_, err = tx.Exec(statement.query)
		}
		if err != nil {
			return fmt.Errorf("finish level-two class contracts (%s): %w", statement.name, err)
		}
	}
	if _, err = tx.Exec(certifiedContentMechanicsOnlyLockDDL); err != nil {
		return err
	}
	return tx.Commit()
}
