package migrations

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"reflect"
)

type proofTable struct {
	name             string
	columns          []string
	constraints      []string
	indexes, trigger bool
}

func proofTables() []proofTable {
	return []proofTable{
		{"roguelike_command_receipts", []string{"response_version", "response_payload", "response_sha256", "response_length"}, []string{"roguelike_command_receipts_storage_version"}, false, false},
		{"character_runtime_commands", []string{"response_version", "response_payload", "response_sha256", "response_length"}, []string{"character_runtime_commands_storage_version"}, false, false},
		{"roguelike_runs", []string{"combat_catalog_ref"}, []string{"roguelike_frozen_catalog_ref"}, false, false},
		{"frozen_combat_catalogs", nil, nil, true, true},
		{"image_jobs", nil, nil, true, true},
	}
}

// The reference is generated by PostgreSQL itself from the exact reviewed DDL
// inside a savepoint and rolled back. This checks real types, defaults, nulls,
// constraints, index definitions and trigger function/enabled state, without
// guessing pg_get_* formatting or trusting IF NOT EXISTS as verification.
func verifyAdditiveSchema(ctx context.Context, tx *sql.Tx) ([]byte, error) {
	actual, err := captureAdditiveSchema(ctx, tx)
	if err != nil {
		return nil, err
	}
	var random [12]byte
	if _, err = rand.Read(random[:]); err != nil {
		return nil, err
	}
	schema := "release_schema_probe_" + hex.EncodeToString(random[:])
	if _, err = tx.ExecContext(ctx, "SAVEPOINT release_schema_proof"); err != nil {
		return nil, err
	}
	if _, err = tx.ExecContext(ctx, "CREATE SCHEMA "+schema+"; SET LOCAL search_path="+schema+",pg_catalog;"+
		"CREATE TABLE roguelike_command_receipts(response jsonb); CREATE TABLE character_runtime_commands(response jsonb); CREATE TABLE roguelike_runs(user_id uuid);"); err != nil {
		return nil, errors.New("cannot create transactional schema proof")
	}
	for _, migration := range additiveRegistry() {
		if err = migration.up(tx); err != nil {
			return nil, errors.New("cannot build reference schema proof")
		}
	}
	expected, err := captureAdditiveSchema(ctx, tx)
	if err != nil {
		return nil, err
	}
	if _, err = tx.ExecContext(ctx, "ROLLBACK TO SAVEPOINT release_schema_proof; RELEASE SAVEPOINT release_schema_proof"); err != nil {
		return nil, err
	}
	if !reflect.DeepEqual(actual, expected) {
		return nil, errors.New("observed additive schema differs from embedded DDL")
	}
	return json.Marshal(actual)
}
func captureAdditiveSchema(ctx context.Context, tx *sql.Tx) (map[string]json.RawMessage, error) {
	result := map[string]json.RawMessage{}
	for _, table := range proofTables() {
		// Null lists select all fields for newly created tables; explicit lists
		// inspect only the new members on historically populated tables.
		var definition []byte
		err := tx.QueryRowContext(ctx, `SELECT jsonb_build_object(
		 'table',CASE WHEN $4 THEN (SELECT jsonb_build_array(c.relkind,c.relpersistence,c.relrowsecurity,c.relforcerowsecurity,c.relispartition,c.relhasrules,
		 (SELECT count(*) FROM pg_policy p WHERE p.polrelid=c.oid),(SELECT count(*) FROM pg_inherits i WHERE i.inhrelid=c.oid)) FROM pg_class c WHERE c.oid=to_regclass($1)) ELSE NULL END,
		 'columns',(SELECT jsonb_agg(jsonb_build_array(a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,pg_get_expr(d.adbin,d.adrelid),a.attidentity,a.attgenerated,
		 (SELECT collname FROM pg_collation WHERE oid=a.attcollation)) ORDER BY a.attname)
		 FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
		 WHERE a.attrelid=to_regclass($1) AND a.attnum>0 AND NOT a.attisdropped AND ($2::text[] IS NULL OR a.attname=ANY($2::text[]))),
		 'constraints',(SELECT jsonb_agg(jsonb_build_array(c.conname,c.contype,c.convalidated,pg_get_constraintdef(c.oid)) ORDER BY c.conname)
		 FROM pg_constraint c WHERE c.conrelid=to_regclass($1) AND ($3::text[] IS NULL OR c.conname=ANY($3::text[]))),
		 'indexes',CASE WHEN $4 THEN (SELECT jsonb_agg(jsonb_build_array(i.relname,x.indisvalid,x.indisready,pg_get_indexdef(x.indexrelid)) ORDER BY i.relname)
		 FROM pg_index x JOIN pg_class i ON i.oid=x.indexrelid WHERE x.indrelid=to_regclass($1)) ELSE NULL END,
		 'triggers',CASE WHEN $5 THEN (SELECT jsonb_agg(jsonb_build_array(t.tgname,t.tgenabled,t.tgtype,pg_get_expr(t.tgqual,t.tgrelid),t.tgattr::text,encode(t.tgargs,'hex'),
		 t.tgdeferrable,t.tginitdeferred,t.tgoldtable,t.tgnewtable,p.proname,p.prosrc,p.provolatile,p.prosecdef,p.proisstrict,p.proleakproof,p.proconfig,l.lanname,
		 p.pronamespace=(SELECT relnamespace FROM pg_class WHERE oid=t.tgrelid),pg_get_function_identity_arguments(p.oid),format_type(p.prorettype,NULL)) ORDER BY t.tgname)
		 FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid JOIN pg_language l ON l.oid=p.prolang WHERE t.tgrelid=to_regclass($1) AND NOT t.tgisinternal) ELSE NULL END)::text`, table.name, table.columns, table.constraints, table.indexes, table.trigger).Scan(&definition)
		if err != nil {
			return nil, errors.New("cannot inspect additive schema")
		}
		// Index SQL qualifies its own relation regardless of search_path. Replace
		// only the current schema prefix; literal function bodies are untouched.
		var namespace string
		if err = tx.QueryRowContext(ctx, "SELECT current_schema()").Scan(&namespace); err != nil {
			return nil, err
		}
		var decoded map[string]interface{}
		if err = json.Unmarshal(definition, &decoded); err != nil {
			return nil, err
		}
		if indexes, ok := decoded["indexes"].([]interface{}); ok {
			for _, entry := range indexes {
				parts := entry.([]interface{})
				definition := parts[3].(string)
				parts[3] = normalizeIndexSchema(definition, namespace)
			}
		}
		result[table.name], err = json.Marshal(decoded)
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}
func normalizeIndexSchema(definition, namespace string) string {
	// The namespace comes from PostgreSQL, and the exact delimited prefix is
	// replaced only in the ON table position, not arbitrary SQL literals.
	for _, prefix := range []string{" ON " + namespace + ".", " ON \"" + namespace + "\"."} {
		for i := 0; i+len(prefix) <= len(definition); i++ {
			if definition[i:i+len(prefix)] == prefix {
				return definition[:i] + " ON " + definition[i+len(prefix):]
			}
		}
	}
	return definition
}
