// АВТОГЕНЕРАЦИЯ — не редактировать вручную.
// Источник: https://new.ttg.club/api/v2/bestiary/search (официальные источники MM/PHB/DMG и др.).
// Всего существ: 639. Обновить: перезапросить API и перегенерировать.
import type { TtgBestiaryRaw } from './ttgBestiaryMap';

export const TTG_BESTIARY_DATA: TtgBestiaryRaw[] = [
  { name: 'Ааракокра аэромант', eng: 'Aarakocra Aeromancer', slug: 'aarakocra-aeromancer-mm', type: 'Элементаль', cr: '4' },
  { name: 'Ааракокра застрельщик', eng: 'Aarakocra Skirmisher', slug: 'aarakocra-skirmisher-mm', type: 'Элементаль', cr: '1/4' },
  { name: 'Аберрантная мёртвая голова', eng: 'Aberrant Death\'s Head', slug: 'aberrant-death-s-head-rhw', type: 'Нежить', cr: '1' },
  { name: 'Аболет', eng: 'Aboleth', slug: 'aboleth-mm', type: 'Аберрация', cr: '10' },
  { name: 'Агент с меткой тени', eng: 'Shadow-Marked Agent', slug: 'shadow-marked-agent-efa', type: 'Гуманоид (эльф)', cr: '7' },
  { name: 'Агент фаэриммов', eng: 'Phaerimm Agent', slug: 'phaerimm-agent-fraif', type: 'Аберрация', cr: '8' },
  { name: 'Адская гончая', eng: 'Hell Hound', slug: 'hell-hound-mm', type: 'Исчадие', cr: '3' },
  { name: 'Азалин Рекс', eng: 'Azalin Rex', slug: 'azalin-rex-rhw', type: 'Нежить', cr: '23' },
  { name: 'Аллозавр', eng: 'Allosaurus', slug: 'allosaurus-mm', type: 'Зверь (динозавр)', cr: '2' },
  { name: 'Анкилозавр', eng: 'Ankylosaurus', slug: 'ankylosaurus-mm', type: 'Зверь (динозавр)', cr: '3' },
  { name: 'Анхег', eng: 'Ankheg', slug: 'ankheg-mm', type: 'Монстр', cr: '2' },
  { name: 'Анхтепот', eng: 'Ankhtepot', slug: 'ankhtepot-rhw', type: 'Нежить', cr: '17' },
  { name: 'Аранея', eng: 'Aranea', slug: 'aranea-fraif', type: 'Монстр', cr: '2' },
  { name: 'Арканалот', eng: 'Arcanaloth', slug: 'arcanaloth-mm', type: 'Исчадие (юголот)', cr: '12' },
  { name: 'Архелон', eng: 'Archelon', slug: 'archelon-mm', type: 'Зверь (динозавр)', cr: '4' },
  { name: 'Архикарга', eng: 'Arch-hag', slug: 'arch-hag-mm', type: 'Фея', cr: '21' },
  { name: 'Архимаг', eng: 'Archmage', slug: 'archmage-mm', type: 'Гуманоид (волшебник)', cr: '12' },
  { name: 'Архисвященник', eng: 'Archpriest', slug: 'archpriest-mm', type: 'Гуманоид (жрец)', cr: '12' },
  { name: 'Ассасин', eng: 'Assassin', slug: 'assassin-mm', type: 'Гуманоид', cr: '8' },
  { name: 'Багбир воин', eng: 'Bugbear Warrior', slug: 'bugbear-warrior-mm', type: 'Фея (гоблиноид)', cr: '1' },
  { name: 'Багбир охотник', eng: 'Bugbear Stalker', slug: 'bugbear-stalker-mm', type: 'Фея (гоблиноид)', cr: '3' },
  { name: 'Балор', eng: 'Balor', slug: 'balor-mm', type: 'Исчадие (демон)', cr: '19' },
  { name: 'Бандит', eng: 'Bandit', slug: 'bandit-mm', type: 'Гуманоид', cr: '1/8' },
  { name: 'Бандит капитан', eng: 'Bandit Captain', slug: 'bandit-captain-mm', type: 'Гуманоид', cr: '2' },
  { name: 'Бандит криминальный лорд', eng: 'Bandit Crime Lord', slug: 'bandit-crime-lord-mm', type: 'Гуманоид', cr: '11' },
  { name: 'Бандит обманщик', eng: 'Bandit Deceiver', slug: 'bandit-deceiver-mm', type: 'Гуманоид', cr: '7' },
  { name: 'Банши', eng: 'Banshee', slug: 'banshee-mm', type: 'Нежить', cr: '4' },
  { name: 'Барлгура', eng: 'Barlgura', slug: 'barlgura-mm', type: 'Исчадие (демон)', cr: '5' },
  { name: 'Бегемот', eng: 'Hippopotamus', slug: 'hippopotamus-mm', type: 'Зверь', cr: '4' },
  { name: 'Безжалостный джаггернаут', eng: 'Relentless Juggernaut', slug: 'relentless-juggernaut-rhw', type: 'Исчадие', cr: '12' },
  { name: 'Безжалостный кошмар', eng: 'Relentless Nightmare', slug: 'relentless-nightmare-rhw', type: 'Исчадие', cr: '11' },
  { name: 'Безжалостный рубака', eng: 'Relentless Slasher', slug: 'relentless-slasher-rhw', type: 'Исчадие', cr: '8' },
  { name: 'Белый медведь', eng: 'Polar Bear', slug: 'polar-bear-mm', type: 'Зверь', cr: '2' },
  { name: 'Берсерк', eng: 'Berserker', slug: 'berserker-mm', type: 'Гуманоид', cr: '2' },
  { name: 'Берсерк командир', eng: 'Berserker Commander', slug: 'berserker-commander-mm', type: 'Гуманоид', cr: '8' },
  { name: 'Бес', eng: 'Imp', slug: 'imp-mm', type: 'Исчадие (дьявол)', cr: '1' },
  { name: 'Бескостный', eng: 'Boneless', slug: 'boneless-rhw', type: 'Нежить', cr: '1' },
  { name: 'Бехир', eng: 'Behir', slug: 'behir-mm', type: 'Монстр', cr: '11' },
  { name: 'Бехолдер', eng: 'Beholder', slug: 'beholder-mm', type: 'Аберрация', cr: '13' },
  { name: 'Благородный', eng: 'Noble', slug: 'noble-mm', type: 'Гуманоид', cr: '1/8' },
  { name: 'Блуждающий огонёк', eng: 'Will-o\'-Wisp', slug: 'will-o-wisp-dmg', type: 'Нежить', cr: '2' },
  { name: 'Боевая лошадь', eng: 'Warhorse', slug: 'warhorse-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Бормочущий ротовик', eng: 'Gibbering Mouther', slug: 'gibbering-mouther-mm', type: 'Аберрация', cr: '2' },
  { name: 'Бородатый дьявол', eng: 'Bearded Devil', slug: 'bearded-devil-mm', type: 'Исчадие (дьявол)', cr: '3' },
  { name: 'Брегган Черная корона', eng: 'Breggan Blackcrown', slug: 'breggan-blackcrown-feq', type: 'Гуманоид (человек, колдун)', cr: '8' },
  { name: 'Бугай', eng: 'Tough', slug: 'tough-mm', type: 'Гуманоид', cr: '1/2' },
  { name: 'Бугай босс', eng: 'Tough Boss', slug: 'tough-boss-mm', type: 'Гуманоид', cr: '4' },
  { name: 'Бурый громила', eng: 'Umber Hulk', slug: 'umber-hulk-mm', type: 'Монстр', cr: '5' },
  { name: 'Бурый медведь', eng: 'Brown Bear', slug: 'brown-bear-mm', type: 'Зверь', cr: '1' },
  { name: 'Быстрокаменная гаргулья', eng: 'Quickstone Gargoyle', slug: 'quickstone-gargoyle-feq', type: 'Элементаль (перевёртыш)', cr: '3' },
  { name: 'Валиндра Тенёмантия', eng: 'Valindra Shadowmantle', slug: 'valindra-shadowmantle-fraif', type: 'Нежить (волшебник)', cr: '21' },
  { name: 'Вампир', eng: 'Vampire', slug: 'vampire-mm', type: 'Нежить', cr: '13' },
  { name: 'Вампир вестник ночи', eng: 'Vampire Nightbringer', slug: 'vampire-nightbringer-mm', type: 'Нежить', cr: '8' },
  { name: 'Вампир повелитель тени', eng: 'Vampire Umbral Lord', slug: 'vampire-umbral-lord-mm', type: 'Нежить', cr: '15' },
  { name: 'Вампир-иллитид', eng: 'Vampire Mind Flayer', slug: 'vampire-mind-flayer-rhw', type: 'Нежить', cr: '5' },
  { name: 'Вампир-инферналист', eng: 'Vampire Infernalist', slug: 'vampire-infernalist-abh', type: 'Нежить (волшебник)', cr: '14' },
  { name: 'Вампир-носферату', eng: 'Vampire Nosferatu', slug: 'vampire-nosferatu-rhw', type: 'Нежить', cr: '8' },
  { name: 'Вампир-смотритель', eng: 'Vampire Warden', slug: 'vampire-warden-abh', type: 'Нежить', cr: '10' },
  { name: 'Василиск', eng: 'Basilisk', slug: 'basilisk-mm', type: 'Монстр', cr: '3' },
  { name: 'Великан Лорвина', eng: 'Lorwyn Giant', slug: 'lorwyn-giant-lfl', type: 'Великан', cr: '6' },
  { name: 'Великан Тенеборья', eng: 'Shadowmoor Giant', slug: 'shadowmoor-giant-lfl', type: 'Великан', cr: '8' },
  { name: 'Верблюд', eng: 'Camel', slug: 'camel-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Верволк', eng: 'Werewolf', slug: 'werewolf-mm', type: 'Монстр (оборотень)', cr: '3' },
  { name: 'Верворон', eng: 'Wereraven', slug: 'wereraven-rhw', type: 'Монстр (оборотень)', cr: '2' },
  { name: 'Верёвочник', eng: 'Roper', slug: 'roper-mm', type: 'Аберрация', cr: '5' },
  { name: 'Веркабан', eng: 'Wereboar', slug: 'wereboar-mm', type: 'Монстр (оборотень)', cr: '4' },
  { name: 'Веркрыса', eng: 'Wererat', slug: 'wererat-mm', type: 'Монстр (оборотень)', cr: '2' },
  { name: 'Вермедведь', eng: 'Werebear', slug: 'werebear-mm', type: 'Монстр (оборотень)', cr: '5' },
  { name: 'Вертигр', eng: 'Weretiger', slug: 'weretiger-mm', type: 'Монстр (оборотень)', cr: '4' },
  { name: 'Верховный миконид', eng: 'Myconid Sovereign', slug: 'myconid-sovereign-mm', type: 'Растение', cr: '2' },
  { name: 'Ветвистая зараза', eng: 'Twig Blight', slug: 'twig-blight-mm', type: 'Растение', cr: '1/8' },
  { name: 'Взрослый белый дракон', eng: 'Adult White Dragon', slug: 'adult-white-dragon-mm', type: 'Дракон (цветной)', cr: '13' },
  { name: 'Взрослый бронзовый дракон', eng: 'Adult Bronze Dragon', slug: 'adult-bronze-dragon-mm', type: 'Дракон (металлический)', cr: '15' },
  { name: 'Взрослый волшебный дракончик', eng: 'Faerie Dragon Adult', slug: 'faerie-dragon-adult-mm', type: 'Дракон', cr: '2' },
  { name: 'Взрослый глубинный дракон', eng: 'Adult Deep Dragon', slug: 'adult-deep-dragon-fraif', type: 'Дракон', cr: '11' },
  { name: 'Взрослый духовный дракон', eng: 'Adult Spirit Dragon', slug: 'adult-spirit-dragon-fraif', type: 'Дракон', cr: '15' },
  { name: 'Взрослый зелёный дракон', eng: 'Adult Green Dragon', slug: 'adult-green-dragon-mm', type: 'Дракон (цветной)', cr: '15' },
  { name: 'Взрослый золотой дракон', eng: 'Adult Gold Dragon', slug: 'adult-gold-dragon-mm', type: 'Дракон (металлический)', cr: '17' },
  { name: 'Взрослый красный дракон', eng: 'Adult Red Dragon', slug: 'adult-red-dragon-mm', type: 'Дракон (цветной)', cr: '17' },
  { name: 'Взрослый латунный дракон', eng: 'Adult Brass Dragon', slug: 'adult-brass-dragon-mm', type: 'Дракон (металлический)', cr: '13' },
  { name: 'Взрослый медный дракон', eng: 'Adult Copper Dragon', slug: 'adult-copper-dragon-mm', type: 'Дракон (металлический)', cr: '14' },
  { name: 'Взрослый миконид', eng: 'Myconid Adult', slug: 'myconid-adult-mm', type: 'Растение', cr: '1/2' },
  { name: 'Взрослый серебряный дракон', eng: 'Adult Silver Dragon', slug: 'adult-silver-dragon-mm', type: 'Дракон (металлический)', cr: '16' },
  { name: 'Взрослый синий дракон', eng: 'Adult Blue Dragon', slug: 'adult-blue-dragon-mm', type: 'Дракон (цветной)', cr: '16' },
  { name: 'Взрослый чёрный дракон', eng: 'Adult Black Dragon', slug: 'adult-black-dragon-mm', type: 'Дракон (цветной)', cr: '14' },
  { name: 'Виверна', eng: 'Wyvern', slug: 'wyvern-mm', type: 'Дракон', cr: '6' },
  { name: 'Виктра Морденхайм', eng: 'Viktra Mordenheim', slug: 'viktra-mordenheim-rhw', type: 'Гуманоид (человек)', cr: '7' },
  { name: 'Вирмлинг белый дракон', eng: 'White Dragon Wyrmling', slug: 'white-dragon-wyrmling-mm', type: 'Дракон', cr: '2' },
  { name: 'Вирмлинг бронзовый дракон', eng: 'Bronze Dragon Wyrmling', slug: 'bronze-dragon-wyrmling-mm', type: 'Дракон (металлический)', cr: '2' },
  { name: 'Вирмлинг зелёный дракон', eng: 'Green Dragon Wyrmling', slug: 'green-dragon-wyrmling-mm', type: 'Дракон (цветной)', cr: '2' },
  { name: 'Вирмлинг золотой дракон', eng: 'Gold Dragon Wyrmling', slug: 'gold-dragon-wyrmling-mm', type: 'Дракон (металлический)', cr: '3' },
  { name: 'Вирмлинг красный дракон', eng: 'Red Dragon Wyrmling', slug: 'red-dragon-wyrmling-mm', type: 'Дракон (цветной)', cr: '4' },
  { name: 'Вирмлинг латунный дракон', eng: 'Brass Dragon Wyrmling', slug: 'brass-dragon-wyrmling-mm', type: 'Дракон (металлический)', cr: '1' },
  { name: 'Вирмлинг медный дракон', eng: 'Copper Dragon Wyrmling', slug: 'copper-dragon-wyrmling-mm', type: 'Дракон (металлический)', cr: '1' },
  { name: 'Вирмлинг серебряный дракон', eng: 'Silver Dragon Wyrmling', slug: 'silver-dragon-wyrmling-mm', type: 'Дракон (металлический)', cr: '2' },
  { name: 'Вирмлинг синий дракон', eng: 'Blue Dragon Wyrmling', slug: 'blue-dragon-wyrmling-mm', type: 'Дракон (цветной)', cr: '3' },
  { name: 'Вирмлинг чёрный дракон', eng: 'Black Dragon Wyrmling', slug: 'black-dragon-wyrmling-mm', type: 'Дракон (цветной)', cr: '2' },
  { name: 'Владеска Драков', eng: 'Vladeska Drakov', slug: 'vladeska-drakov-rhw', type: 'Гуманоид (человек)', cr: '12' },
  { name: 'Владыка зверей', eng: 'Animal Lord', slug: 'animal-lord-mm', type: 'Небожитель', cr: '20' },
  { name: 'Водная аномалия', eng: 'Water Weird', slug: 'water-weird-mm', type: 'Элементаль', cr: '3' },
  { name: 'Водянник', eng: 'Merrow', slug: 'merrow-mm', type: 'Монстр', cr: '2' },
  { name: 'Воин ветеран', eng: 'Warrior Veteran', slug: 'warrior-veteran-mm', type: 'Гуманоид', cr: '3' },
  { name: 'Воин командир', eng: 'Warrior Commander', slug: 'warrior-commander-mm', type: 'Гуманоид', cr: '10' },
  { name: 'Воин пехотинец', eng: 'Warrior Infantry', slug: 'warrior-infantry-mm', type: 'Гуманоид', cr: '1/8' },
  { name: 'Волк', eng: 'Wolf', slug: 'wolf-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Воплощение бренности', eng: 'Incarnation of Transience', slug: 'incarnation-of-transience-lfl', type: 'Фея', cr: '7' },
  { name: 'Воплощение яркости', eng: 'Incarnation of Vibrance', slug: 'incarnation-of-vibrance-lfl', type: 'Фея', cr: '10' },
  { name: 'Ворг', eng: 'Worg', slug: 'worg-mm', type: 'Фея', cr: '1/2' },
  { name: 'Восковой двойник', eng: 'Waxwork', slug: 'waxwork-rhw', type: 'Конструкт', cr: '3' },
  { name: 'Врок', eng: 'Vrock', slug: 'vrock-mm', type: 'Исчадие (демон)', cr: '6' },
  { name: 'Вурдалак', eng: 'Ghast', slug: 'ghast-mm', type: 'Нежить', cr: '2' },
  { name: 'Вурдалак могильщик', eng: 'Ghast Gravecaller', slug: 'ghast-gravecaller-mm', type: 'Нежить', cr: '6' },
  { name: 'Высший Эмиссар порождения звезд', eng: 'Greater Star Spawn Emissary', slug: 'greater-star-spawn-emissary-rhw', type: 'Аберрация', cr: '21' },
  { name: 'Вьющаяся зараза', eng: 'Vine Blight', slug: 'vine-blight-mm', type: 'Растение', cr: '1/2' },
  { name: 'Газовая спора', eng: 'Gas Spore Fungus', slug: 'gas-spore-fungus-mm', type: 'Растение', cr: '1/2' },
  { name: 'Галеб дур', eng: 'Galeb Duhr', slug: 'galeb-duhr-mm', type: 'Элементаль', cr: '6' },
  { name: 'Гантии\'каас', eng: 'Gantii\'kaas', slug: 'gantii-kaas-feq', type: 'Фея', cr: '5' },
  { name: 'Гаргулья', eng: 'Gargoyle', slug: 'gargoyle-mm', type: 'Элементаль', cr: '2' },
  { name: 'Гаргулья демонического стекла', eng: 'Demonglass Gargoyle', slug: 'demonglass-gargoyle-feq', type: 'Исчадие', cr: '5' },
  { name: 'Гарпия', eng: 'Harpy', slug: 'harpy-mm', type: 'Монстр', cr: '1' },
  { name: 'Гигантская акула', eng: 'Giant Shark', slug: 'giant-shark-mm', type: 'Зверь', cr: '5' },
  { name: 'Гигантская гиена', eng: 'Giant Hyena', slug: 'giant-hyena-mm', type: 'Зверь', cr: '1' },
  { name: 'Гигантская жаба', eng: 'Giant Toad', slug: 'giant-toad-mm', type: 'Зверь', cr: '1' },
  { name: 'Гигантская крыса', eng: 'Giant Rat', slug: 'giant-rat-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Гигантская куница', eng: 'Giant Weasel', slug: 'giant-weasel-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Гигантская летучая мышь', eng: 'Giant Bat', slug: 'giant-bat-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантская лягушка', eng: 'Giant Frog', slug: 'giant-frog-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантская многоножка', eng: 'Giant Centipede', slug: 'giant-centipede-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантская обезьяна', eng: 'Giant Ape', slug: 'giant-ape-mm', type: 'Зверь', cr: '7' },
  { name: 'Гигантская оса', eng: 'Giant Wasp', slug: 'giant-wasp-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Гигантская сова', eng: 'Giant Owl', slug: 'giant-owl-mm', type: 'Небожитель', cr: '1/8' },
  { name: 'Гигантская ядовитая змея', eng: 'Giant Venomous Snake', slug: 'giant-venomous-snake-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантская ящерица', eng: 'Giant Lizard', slug: 'giant-lizard-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантский барсук', eng: 'Giant Badger', slug: 'giant-badger-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантский гриф', eng: 'Giant Vulture', slug: 'giant-vulture-mm', type: 'Монстр', cr: '1' },
  { name: 'Гигантский кабан', eng: 'Giant Boar', slug: 'giant-boar-mm', type: 'Зверь', cr: '2' },
  { name: 'Гигантский кальмар', eng: 'Giant Squid', slug: 'giant-squid-mm', type: 'Зверь', cr: '6' },
  { name: 'Гигантский козёл', eng: 'Giant Goat', slug: 'giant-goat-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Гигантский краб', eng: 'Giant Crab', slug: 'giant-crab-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Гигантский крокодил', eng: 'Giant Crocodile', slug: 'giant-crocodile-mm', type: 'Зверь', cr: '5' },
  { name: 'Гигантский лось', eng: 'Giant Elk', slug: 'giant-elk-mm', type: 'Небожитель', cr: '2' },
  { name: 'Гигантский морской конек', eng: 'Giant Seahorse', slug: 'giant-seahorse-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Гигантский орёл', eng: 'Giant Eagle', slug: 'giant-eagle-mm', type: 'Небожитель', cr: '1' },
  { name: 'Гигантский осьминог', eng: 'Giant Octopus', slug: 'giant-octopus-mm', type: 'Зверь', cr: '1' },
  { name: 'Гигантский паук', eng: 'Giant Spider', slug: 'giant-spider-mm', type: 'Зверь', cr: '1' },
  { name: 'Гигантский паук-волк', eng: 'Giant Wolf Spider', slug: 'giant-wolf-spider-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Гигантский скорпион', eng: 'Giant Scorpion', slug: 'giant-scorpion-mm', type: 'Зверь', cr: '3' },
  { name: 'Гигантский топороклюв', eng: 'Giant Axe Beak', slug: 'giant-axe-beak-mm', type: 'Монстр', cr: '5' },
  { name: 'Гигантский удав', eng: 'Giant Constrictor Snake', slug: 'giant-constrictor-snake-mm', type: 'Зверь', cr: '2' },
  { name: 'Гидра', eng: 'Hydra', slug: 'hydra-mm', type: 'Монстр', cr: '8' },
  { name: 'Гиппогриф', eng: 'Hippogriff', slug: 'hippogriff-mm', type: 'Монстр', cr: '1' },
  { name: 'Гитцерай зерт', eng: 'Githzerai Zerth', slug: 'githzerai-zerth-mm', type: 'Аберрация (гит)', cr: '6' },
  { name: 'Гитцерай монах', eng: 'Githzerai Monk', slug: 'githzerai-monk-mm', type: 'Аберрация (гит)', cr: '2' },
  { name: 'Гитцерай псионик', eng: 'Githzerai Psion', slug: 'githzerai-psion-mm', type: 'Аберрация (гит)', cr: '12' },
  { name: 'Гитьянки воин', eng: 'Githyanki Warrior', slug: 'githyanki-warrior-mm', type: 'Аберрация (гит)', cr: '3' },
  { name: 'Гитьянки дракомант', eng: 'Githyanki Dracomancer', slug: 'githyanki-dracomancer-mm', type: 'Аберрация (гит)', cr: '16' },
  { name: 'Гитьянки рыцарь', eng: 'Githyanki Knight', slug: 'githyanki-knight-mm', type: 'Аберрация (гит)', cr: '8' },
  { name: 'Глабрезу', eng: 'Glabrezu', slug: 'glabrezu-mm', type: 'Исчадие (демон)', cr: '9' },
  { name: 'Гладиатор', eng: 'Gladiator', slug: 'gladiator-mm', type: 'Гуманоид', cr: '5' },
  { name: 'Глашатай-висельник', eng: 'Gallows Speaker', slug: 'gallows-speaker-rhw', type: 'Нежить', cr: '6' },
  { name: 'Глиняный голем', eng: 'Clay Golem', slug: 'clay-golem-mm', type: 'Конструкт', cr: '9' },
  { name: 'Глубинный дракон вирмлинг', eng: 'Deep Dragon Wyrmling', slug: 'deep-dragon-wyrmling-fraif', type: 'Дракон', cr: '1' },
  { name: 'Гнолл вождь стаи', eng: 'Gnoll Pack Lord', slug: 'gnoll-pack-lord-mm', type: 'Исчадие', cr: '2' },
  { name: 'Гнолл воин', eng: 'Gnoll Warrior', slug: 'gnoll-warrior-mm', type: 'Исчадие', cr: '1/2' },
  { name: 'Гнолл демоньяк', eng: 'Gnoll Demoniac', slug: 'gnoll-demoniac-mm', type: 'Исчадие', cr: '8' },
  { name: 'Гнолл клык Йеногу', eng: 'Gnoll Fang of Yeenoghu', slug: 'gnoll-fang-of-yeenoghu-mm', type: 'Исчадие', cr: '4' },
  { name: 'Гоблин босс', eng: 'Goblin Boss', slug: 'goblin-boss-mm', type: 'Фея (гоблиноид)', cr: '1' },
  { name: 'Гоблин буяг', eng: 'Goblin Hexer', slug: 'goblin-hexer-mm', type: 'Фея (гоблиноид)', cr: '3' },
  { name: 'Гоблин воин', eng: 'Goblin Warrior', slug: 'goblin-warrior-mm', type: 'Фея (гоблиноид)', cr: '1/4' },
  { name: 'Гоблин демонического стекла', eng: 'Demonglass Goblin', slug: 'demonglass-goblin-feq', type: 'Гуманоид (гоблинойд)', cr: '1/4' },
  { name: 'Гоблин прислужник', eng: 'Goblin Minion', slug: 'goblin-minion-mm', type: 'Фея (гоблиноид)', cr: '1/8' },
  { name: 'Головорез Дома Тарканан', eng: 'Tarkanan Ruffian', slug: 'tarkanan-ruffian-efa', type: 'Гуманоид', cr: '1' },
  { name: 'Горгона', eng: 'Gorgon', slug: 'gorgon-mm', type: 'Конструкт', cr: '5' },
  { name: 'Гористо', eng: 'Goristro', slug: 'goristro-mm', type: 'Исчадие (демон)', cr: '17' },
  { name: 'Грелл', eng: 'Grell', slug: 'grell-mm', type: 'Аберрация', cr: '3' },
  { name: 'Гремишка', eng: 'Gremishka', slug: 'gremishka-rhw', type: 'Монстр', cr: '2' },
  { name: 'Грик', eng: 'Grick', slug: 'grick-mm', type: 'Аберрация', cr: '2' },
  { name: 'Гримлок', eng: 'Grimlock', slug: 'grimlock-mm', type: 'Аберрация', cr: '1/4' },
  { name: 'Грифон', eng: 'Griffon', slug: 'griffon-mm', type: 'Монстр', cr: '2' },
  { name: 'Громила Дааска', eng: 'Daask Bruiser', slug: 'daask-bruiser-efa', type: 'Гуманоид (гнолл)', cr: '9' },
  { name: 'Грязевой мефит', eng: 'Mud Mephit', slug: 'mud-mephit-mm', type: 'Элементаль', cr: '1/4' },
  { name: 'Гуг', eng: 'Gug', slug: 'gug-rhw', type: 'Аберрация', cr: '12' },
  { name: 'Дао', eng: 'Dao', slug: 'dao-mm', type: 'Элементаль (гений)', cr: '11' },
  { name: 'Дева-лебедь', eng: 'Swanmay', slug: 'swanmay-fraif', type: 'Фея', cr: '3' },
  { name: 'Демилич', eng: 'Demilich', slug: 'demilich-mm', type: 'Нежить', cr: '18' },
  { name: 'Дерево мёртвых голов', eng: 'Death\'s Head Tree', slug: 'death-s-head-tree-rhw', type: 'Растение', cr: '4' },
  { name: 'Дженнифер Уэзермей-Фоксгроув', eng: 'Gennifer Weathermay-Foxgrove', slug: 'gennifer-weathermay-foxgrove-rhw', type: 'Гуманоид (человек, оборотень)', cr: '3' },
  { name: 'Джинн', eng: 'Djinni', slug: 'djinni-mm', type: 'Элементаль (гений)', cr: '11' },
  { name: 'Долгул', eng: 'Dolguul', slug: 'dolguul-feq', type: 'Аберрация', cr: '4' },
  { name: 'Доппельгангер', eng: 'Doppelganger', slug: 'doppelganger-mm', type: 'Монстр', cr: '3' },
  { name: 'Драколич', eng: 'Dracolich', slug: 'dracolich-mm', type: 'Нежить', cr: '17' },
  { name: 'Дракочерепаха', eng: 'Dragon Turtle', slug: 'dragon-turtle-mm', type: 'Дракон', cr: '17' },
  { name: 'Драук', eng: 'Drider', slug: 'drider-mm', type: 'Монстр', cr: '6' },
  { name: 'Древесная зараза', eng: 'Tree Blight', slug: 'tree-blight-mm', type: 'Растение', cr: '7' },
  { name: 'Древний белый дракон', eng: 'Ancient White Dragon', slug: 'ancient-white-dragon-mm', type: 'Дракон (цветной)', cr: '20' },
  { name: 'Древний бронзовый дракон', eng: 'Ancient Bronze Dragon', slug: 'ancient-bronze-dragon-mm', type: 'Дракон (металлический)', cr: '22' },
  { name: 'Древний глубинный дракон', eng: 'Ancient Deep Dragon', slug: 'ancient-deep-dragon-fraif', type: 'Дракон', cr: '18' },
  { name: 'Древний грик', eng: 'Grick Ancient', slug: 'grick-ancient-mm', type: 'Аберрация', cr: '7' },
  { name: 'Древний духовный дракон', eng: 'Ancient Spirit Dragon', slug: 'ancient-spirit-dragon-fraif', type: 'Дракон', cr: '22' },
  { name: 'Древний зелёный дракон', eng: 'Ancient Green Dragon', slug: 'ancient-green-dragon-mm', type: 'Дракон (цветной)', cr: '22' },
  { name: 'Древний золотой дракон', eng: 'Ancient Gold Dragon', slug: 'ancient-gold-dragon-mm', type: 'Дракон (металлический)', cr: '24' },
  { name: 'Древний красный дракон', eng: 'Ancient Red Dragon', slug: 'ancient-red-dragon-mm', type: 'Дракон (цветной)', cr: '24' },
  { name: 'Древний латунный дракон', eng: 'Ancient Brass Dragon', slug: 'ancient-brass-dragon-mm', type: 'Дракон (металлический)', cr: '20' },
  { name: 'Древний медный дракон', eng: 'Ancient Copper Dragon', slug: 'ancient-copper-dragon-mm', type: 'Дракон (металлический)', cr: '21' },
  { name: 'Древний серебряный дракон', eng: 'Ancient Silver Dragon', slug: 'ancient-silver-dragon-mm', type: 'Дракон (металлический)', cr: '23' },
  { name: 'Древний синий дракон', eng: 'Ancient Blue Dragon', slug: 'ancient-blue-dragon-mm', type: 'Дракон (цветной)', cr: '23' },
  { name: 'Древний фаэримм', eng: 'Phaerimm Elder', slug: 'phaerimm-elder-nf', type: 'Аберрация', cr: '14' },
  { name: 'Древний чёрный дракон', eng: 'Ancient Black Dragon', slug: 'ancient-black-dragon-mm', type: 'Дракон (цветной)', cr: '21' },
  { name: 'Древняя сущность', eng: 'Elder Thing', slug: 'elder-thing-rhw', type: 'Аберрация', cr: '14' },
  { name: 'Дретч', eng: 'Dretch', slug: 'dretch-mm', type: 'Исчадие (демон)', cr: '1/4' },
  { name: 'Дриада', eng: 'Dryad', slug: 'dryad-mm', type: 'Фея', cr: '1' },
  { name: 'Дроу жрица Ллос', eng: 'Drow Priestess of Lolth', slug: 'drow-priestess-of-lolth-fraif', type: 'Гуманоид (эльф)', cr: '8' },
  { name: 'Дроу Ллос', eng: 'Drow of Lolth', slug: 'drow-of-lolth-fraif', type: 'Гуманоид (эльф)', cr: '1/4' },
  { name: 'Дроу маг Ллос', eng: 'Drow Mage of Lolth', slug: 'drow-mage-of-lolth-fraif', type: 'Гуманоид (эльф)', cr: '7' },
  { name: 'Дроу элитный воин Ллос', eng: 'Drow Elite Warrior of Lolth', slug: 'drow-elite-warrior-of-lolth-fraif', type: 'Гуманоид (эльф)', cr: '5' },
  { name: 'Друид', eng: 'Druid', slug: 'druid-mm', type: 'Гуманоид', cr: '2' },
  { name: 'Дуллахан', eng: 'Dullahan', slug: 'dullahan-rhw', type: 'Нежить', cr: '10' },
  { name: 'Духовная нага', eng: 'Spirit Naga', slug: 'spirit-naga-mm', type: 'Исчадие', cr: '8' },
  { name: 'Духовный дракон вирмлинг', eng: 'Spirit Dragon Wyrmling', slug: 'spirit-dragon-wyrmling-fraif', type: 'Дракон', cr: '2' },
  { name: 'Дымовой мефит', eng: 'Smoke Mephit', slug: 'smoke-mephit-mm', type: 'Элементаль', cr: '1/4' },
  { name: 'Дьявол оратор', eng: 'Speaker Devil', slug: 'speaker-devil-abh', type: 'Исчадие (дьявол)', cr: '12' },
  { name: 'Дьявол цепей', eng: 'Chain Devil', slug: 'chain-devil-mm', type: 'Исчадие (дьявол)', cr: '8' },
  { name: 'Дьявол-жнец', eng: 'Harvester Devil', slug: 'harvester-devil-abh', type: 'Исчадие (дьявол)', cr: '3' },
  { name: 'Дэв', eng: 'Deva', slug: 'deva-mm', type: 'Небожитель (ангел)', cr: '10' },
  { name: 'Единорог', eng: 'Unicorn', slug: 'unicorn-mm', type: 'Небожитель', cr: '5' },
  { name: 'Ездовая лошадь', eng: 'Riding Horse', slug: 'riding-horse-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Жаболюд болотный мудрец', eng: 'Bullywug Bog Sage', slug: 'bullywug-bog-sage-mm', type: 'Фея', cr: '4' },
  { name: 'Жаболюд воин', eng: 'Bullywug Warrior', slug: 'bullywug-warrior-mm', type: 'Фея', cr: '1/4' },
  { name: 'Желатиновый куб', eng: 'Gelatinous Cube', slug: 'gelatinous-cube-mm', type: 'Слизь', cr: '2' },
  { name: 'Железный голем', eng: 'Iron Golem', slug: 'iron-golem-mm', type: 'Конструкт', cr: '16' },
  { name: 'Жентилар-паладин Бэйна', eng: 'Zhentilar Paladin of Bane', slug: 'zhentilar-paladin-of-bane-fraif', type: 'Гуманоид', cr: '4' },
  { name: 'Жентилар-солдат', eng: 'Zhentilar Soldier', slug: 'zhentilar-soldier-fraif', type: 'Гуманоид', cr: '1' },
  { name: 'Жрец Осибуса', eng: 'Priest of Osybus', slug: 'priest-of-osybus-rhw', type: 'Гуманоид', cr: '6' },
  { name: 'Жрец-отравитель Вулкоора', eng: 'Vulkoori Venom Priest', slug: 'vulkoori-venom-priest-efa', type: 'Гуманоид (эльф)', cr: '2' },
  { name: 'Зараза Галтиас', eng: 'Gulthias Blight', slug: 'gulthias-blight-mm', type: 'Растение', cr: '16' },
  { name: 'Зверь Малара', eng: 'Beast of Malar', slug: 'beast-of-malar-fraif', type: 'Монстр', cr: '11' },
  { name: 'Зелёная карга', eng: 'Green Hag', slug: 'green-hag-mm', type: 'Фея', cr: '3' },
  { name: 'Зелёный слаад', eng: 'Green Slaad', slug: 'green-slaad-mm', type: 'Аберрация', cr: '8' },
  { name: 'Земляной магин', eng: 'Terran Magen', slug: 'terran-magen-nf', type: 'Конструкт', cr: '8' },
  { name: 'Зимний волк', eng: 'Winter Wolf', slug: 'winter-wolf-mm', type: 'Монстр', cr: '3' },
  { name: 'Злан', eng: 'Zlan', slug: 'zlan-fraif', type: 'Нежить (волшебник)', cr: '18' },
  { name: 'Золотистое желе', eng: 'Ochre Jelly', slug: 'ochre-jelly-mm', type: 'Слизь', cr: '2' },
  { name: 'Зомби', eng: 'Zombie', slug: 'zombie-mm', type: 'Нежить', cr: '1/4' },
  { name: 'Зомби бехолдер', eng: 'Beholder Zombie', slug: 'beholder-zombie-mm', type: 'Нежить', cr: '5' },
  { name: 'Зомби огр', eng: 'Ogre Zombie', slug: 'ogre-zombie-mm', type: 'Нежить', cr: '2' },
  { name: 'Зомби разносчик чумы', eng: 'Zombie Plague Spreader', slug: 'zombie-plague-spreader-rhw', type: 'Нежить', cr: '4' },
  { name: 'Зомби-сгусток', eng: 'Zombie Clot', slug: 'zombie-clot-rhw', type: 'Нежить', cr: '6' },
  { name: 'Зорн', eng: 'Xorn', slug: 'xorn-mm', type: 'Элементаль', cr: '5' },
  { name: 'Иван Дилисния', eng: 'Ivan Dilisnya', slug: 'ivan-dilisnya-rhw', type: 'Гуманоид (человек)', cr: '5' },
  { name: 'Ивана Боритси', eng: 'Ivana Boritsi', slug: 'ivana-boritsi-rhw', type: 'Гуманоид (человек)', cr: '5' },
  { name: 'Игольчатая зараза', eng: 'Needle Blight', slug: 'needle-blight-mm', type: 'Растение', cr: '1/4' },
  { name: 'Игольчатый дьявол', eng: 'Spined Devil', slug: 'spined-devil-mm', type: 'Исчадие (дьявол)', cr: '2' },
  { name: 'Изобретатель Дома Каннит', eng: 'Cannith Artificer', slug: 'cannith-artificer-efa', type: 'Гуманоид (человек)', cr: '4' },
  { name: 'Иллитид', eng: 'Mind Flayer', slug: 'mind-flayer-mm', type: 'Аберрация', cr: '7' },
  { name: 'Иллитид арканист', eng: 'Mind Flayer Arcanist', slug: 'mind-flayer-arcanist-mm', type: 'Аберрация', cr: '11' },
  { name: 'Инквизитор Меча', eng: 'Inquisitor of the Sword', slug: 'inquisitor-of-the-sword-rhw', type: 'Гуманоид', cr: '8' },
  { name: 'Инквизитор Огня Разума', eng: 'Inquisitor of the Mind Fire', slug: 'inquisitor-of-the-mind-fire-rhw', type: 'Гуманоид', cr: '8' },
  { name: 'Инквизитор Тома', eng: 'Inquisitor of the Tome', slug: 'inquisitor-of-the-tome-rhw', type: 'Гуманоид', cr: '8' },
  { name: 'Инкуб', eng: 'Incubus', slug: 'incubus-mm', type: 'Исчадие', cr: '4' },
  { name: 'Инфернальный идол', eng: 'Fiendish Icon', slug: 'fiendish-icon-abh', type: 'Конструкт', cr: '1' },
  { name: 'Инфильтратор Грёзной Тьмы', eng: 'Dreaming Dark Infiltrator', slug: 'dreaming-dark-infiltrator-efa', type: 'Гуманоид', cr: '7' },
  { name: 'Исполнитель', eng: 'Performer', slug: 'performer-mm', type: 'Гуманоид', cr: '1/2' },
  { name: 'Исполнитель легенда', eng: 'Performer Legend', slug: 'performer-legend-mm', type: 'Гуманоид', cr: '10' },
  { name: 'Исполнитель маэстро', eng: 'Performer Maestro', slug: 'performer-maestro-mm', type: 'Гуманоид', cr: '6' },
  { name: 'Истребитель разума Грёзной Тьмы', eng: 'Dreaming Dark Mindkiller', slug: 'dreaming-dark-mindkiller-efa', type: 'Гуманоид', cr: '11' },
  { name: 'Исчадие пропасти', eng: 'Pit Fiend', slug: 'pit-fiend-mm', type: 'Исчадие (дьявол)', cr: '20' },
  { name: 'Ифрит', eng: 'Efreeti', slug: 'efreeti-mm', type: 'Элементаль (гений)', cr: '11' },
  { name: 'Йети', eng: 'Yeti', slug: 'yeti-mm', type: 'Монстр', cr: '3' },
  { name: 'Йитианец', eng: 'Yithian', slug: 'yithian-rhw', type: 'Аберрация', cr: '15' },
  { name: 'Йоклол', eng: 'Yochlol', slug: 'yochlol-mm', type: 'Исчадие (демон)', cr: '10' },
  { name: 'Кабан', eng: 'Boar', slug: 'boar-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Камбион', eng: 'Cambion', slug: 'cambion-mm', type: 'Исчадие', cr: '5' },
  { name: 'Каменный великан', eng: 'Stone Giant', slug: 'stone-giant-mm', type: 'Великан', cr: '7' },
  { name: 'Каменный голем', eng: 'Stone Golem', slug: 'stone-golem-mm', type: 'Конструкт', cr: '10' },
  { name: 'Капля аннигиляции', eng: 'Blob of Annihilation', slug: 'blob-of-annihilation-mm', type: 'Слизь (титан)', cr: '23' },
  { name: 'Карас Чембриль', eng: 'Karas Chembryl', slug: 'karas-chembryl-fraif', type: 'Гуманоид (человек)', cr: '8' },
  { name: 'Каратель Дома Ориен', eng: 'Orien Enforcer', slug: 'orien-enforcer-efa', type: 'Гуманоид (человек)', cr: '4' },
  { name: 'Кваггот', eng: 'Quaggoth', slug: 'quaggoth-mm', type: 'Монстр', cr: '2' },
  { name: 'Кваггот тонот', eng: 'Quaggoth Thonot', slug: 'quaggoth-thonot-mm', type: 'Монстр', cr: '3' },
  { name: 'Квазит', eng: 'Quasit', slug: 'quasit-mm', type: 'Исчадие (демон)', cr: '1' },
  { name: 'Кенку', eng: 'Kenku', slug: 'kenku-mm', type: 'Монстр', cr: '1/4' },
  { name: 'Кентавр воин', eng: 'Centaur Trooper', slug: 'centaur-trooper-mm', type: 'Фея', cr: '2' },
  { name: 'Кентавр хранитель', eng: 'Centaur Warden', slug: 'centaur-warden-mm', type: 'Фея', cr: '7' },
  { name: 'Коатль', eng: 'Couatl', slug: 'couatl-mm', type: 'Небожитель', cr: '4' },
  { name: 'Кобольд воин', eng: 'Kobold Warrior', slug: 'kobold-warrior-mm', type: 'Дракон', cr: '1/8' },
  { name: 'Колосс', eng: 'Colossus', slug: 'colossus-mm', type: 'Конструкт (титан)', cr: '25' },
  { name: 'Командир Изумрудного Когтя', eng: 'Emerald Claw Commander', slug: 'emerald-claw-commander-efa', type: 'Гуманоид', cr: '4' },
  { name: 'Конечность тролля', eng: 'Troll Limb', slug: 'troll-limb-mm', type: 'Великан', cr: '1/2' },
  { name: 'Контрабандист Дома Боромар', eng: 'Boromar Smuggler', slug: 'boromar-smuggler-efa', type: 'Гуманоид (полурослик)', cr: '1/2' },
  { name: 'Королева Покинутых', eng: 'Queen Forfallen', slug: 'queen-forfallen-fraif', type: 'Конструкт', cr: '10' },
  { name: 'Король Серый Палец', eng: 'King Grayfinger', slug: 'king-grayfinger-feq', type: 'Фея', cr: '23' },
  { name: 'Косатка', eng: 'Killer Whale', slug: 'killer-whale-mm', type: 'Зверь', cr: '3' },
  { name: 'Костяная нага', eng: 'Bone Naga', slug: 'bone-naga-mm', type: 'Нежить', cr: '4' },
  { name: 'Костяной дьявол', eng: 'Bone Devil', slug: 'bone-devil-mm', type: 'Исчадие (дьявол)', cr: '9' },
  { name: 'Котловой маген', eng: 'Caldron Magen', slug: 'caldron-magen-nf', type: 'Конструкт', cr: '4' },
  { name: 'Кошмар', eng: 'Nightmare', slug: 'nightmare-mm', type: 'Исчадие', cr: '3' },
  { name: 'Кракен', eng: 'Kraken', slug: 'kraken-mm', type: 'Монстр (титан)', cr: '23' },
  { name: 'Красный слаад', eng: 'Red Slaad', slug: 'red-slaad-mm', type: 'Аберрация', cr: '5' },
  { name: 'Кровавый ястреб', eng: 'Blood Hawk', slug: 'blood-hawk-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Кровопийца', eng: 'Stirge', slug: 'stirge-mm', type: 'Монстр', cr: '1/8' },
  { name: 'Крокодил', eng: 'Crocodile', slug: 'crocodile-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Крылатый кобольд', eng: 'Winged Kobold', slug: 'winged-kobold-mm', type: 'Дракон', cr: '1/4' },
  { name: 'Крюкастый ужас', eng: 'Hook Horror', slug: 'hook-horror-mm', type: 'Монстр', cr: '3' },
  { name: 'Ктулху', eng: 'Cthulhu', slug: 'cthulhu-rhw', type: 'Аберрация', cr: '25' },
  { name: 'Культист', eng: 'Cultist', slug: 'cultist-mm', type: 'Гуманоид', cr: '1/8' },
  { name: 'Культист аберрации', eng: 'Aberrant Cultist', slug: 'aberrant-cultist-mm', type: 'Гуманоид', cr: '8' },
  { name: 'Культист Баала', eng: 'Cultist of Bhaal', slug: 'cultist-of-bhaal-fraif', type: 'Гуманоид', cr: '7' },
  { name: 'Культист Бейна', eng: 'Cultist of Bane', slug: 'cultist-of-bane-fraif', type: 'Гуманоид', cr: '9' },
  { name: 'Культист иерофант', eng: 'Cultist Hierophant', slug: 'cultist-hierophant-mm', type: 'Гуманоид', cr: '10' },
  { name: 'Культист исчадия', eng: 'Fiend Cultist', slug: 'fiend-cultist-mm', type: 'Гуманоид', cr: '8' },
  { name: 'Культист Миркула', eng: 'Cultist of Myrkul', slug: 'cultist-of-myrkul-fraif', type: 'Гуманоид', cr: '11' },
  { name: 'Культист смерти', eng: 'Death Cultist', slug: 'death-cultist-mm', type: 'Гуманоид', cr: '8' },
  { name: 'Культист стихии', eng: 'Elemental Cultist', slug: 'elemental-cultist-mm', type: 'Гуманоид', cr: '8' },
  { name: 'Культист фанатик', eng: 'Cultist Fanatic', slug: 'cultist-fanatic-mm', type: 'Гуманоид', cr: '2' },
  { name: 'Куо-тоа', eng: 'Kuo-toa', slug: 'kuo-toa-mm', type: 'Аберрация', cr: '1/4' },
  { name: 'Куо-тоа архисвященник', eng: 'Kuo-toa Archpriest', slug: 'kuo-toa-archpriest-mm', type: 'Аберрация', cr: '6' },
  { name: 'Куо-тоа кнут', eng: 'Kuo-toa Whip', slug: 'kuo-toa-whip-mm', type: 'Аберрация', cr: '1' },
  { name: 'Куо-тоа наставник', eng: 'Kuo-toa Monitor', slug: 'kuo-toa-monitor-mm', type: 'Аберрация', cr: '3' },
  { name: 'Куролиск', eng: 'Cockatrice', slug: 'cockatrice-mm', type: 'Монстр', cr: '1/2' },
  { name: 'Куролиск регент', eng: 'Cockatrice Regent', slug: 'cockatrice-regent-mm', type: 'Монстр', cr: '8' },
  { name: 'Ламия', eng: 'Lamia', slug: 'lamia-mm', type: 'Исчадие', cr: '4' },
  { name: 'Лев', eng: 'Lion', slug: 'lion-mm', type: 'Зверь', cr: '1' },
  { name: 'Ледяной дьявол', eng: 'Ice Devil', slug: 'ice-devil-mm', type: 'Исчадие (дьявол)', cr: '14' },
  { name: 'Ледяной мефит', eng: 'Ice Mephit', slug: 'ice-mephit-mm', type: 'Элементаль', cr: '1/2' },
  { name: 'Летающая змея', eng: 'Flying Snake', slug: 'flying-snake-mm', type: 'Монстр', cr: '1/8' },
  { name: 'Лиловый гриб', eng: 'Violet Fungus', slug: 'violet-fungus-mm', type: 'Растение', cr: '1/4' },
  { name: 'Лиловый некрогромила', eng: 'Violet Fungus Necrohulk', slug: 'violet-fungus-necrohulk-mm', type: 'Растение', cr: '7' },
  { name: 'Лич', eng: 'Lich', slug: 'lich-mm', type: 'Нежить (волшебник)', cr: '21' },
  { name: 'Лорд мумия', eng: 'Mummy Lord', slug: 'mummy-lord-mm', type: 'Нежить (жрец)', cr: '15' },
  { name: 'Лорд Сот из Ситикуса', eng: 'Lord Soth of Sithicus', slug: 'lord-soth-of-sithicus-rhw', type: 'Нежить', cr: '19' },
  { name: 'Лори Уэзермей-Фоксгроув', eng: 'Laurie Weathermay-Foxgrove', slug: 'laurie-weathermay-foxgrove-rhw', type: 'Гуманоид (человек)', cr: '3' },
  { name: 'Лось', eng: 'Elk', slug: 'elk-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Лу-гару', eng: 'Loup Garou', slug: 'loup-garou-rhw', type: 'Монстр (оборотень)', cr: '13' },
  { name: 'Людоящер вождь', eng: 'Lizardfolk Sovereign', slug: 'lizardfolk-sovereign-mm', type: 'Элементаль', cr: '4' },
  { name: 'Людоящер геомант', eng: 'Lizardfolk Geomancer', slug: 'lizardfolk-geomancer-mm', type: 'Элементаль', cr: '2' },
  { name: 'Лютый волк', eng: 'Dire Wolf', slug: 'dire-wolf-mm', type: 'Зверь', cr: '1' },
  { name: 'Лютый ворг', eng: 'Dire Worg', slug: 'dire-worg-mm', type: 'Фея', cr: '10' },
  { name: 'Маг', eng: 'Mage', slug: 'mage-mm', type: 'Гуманоид (волшебник)', cr: '6' },
  { name: 'Маг ученик', eng: 'Mage Apprentice', slug: 'mage-apprentice-mm', type: 'Гуманоид (волшебник)', cr: '2' },
  { name: 'Магмин', eng: 'Magmin', slug: 'magmin-mm', type: 'Элементаль', cr: '1/2' },
  { name: 'Магмовый мефит', eng: 'Magma Mephit', slug: 'magma-mephit-mm', type: 'Элементаль', cr: '1/2' },
  { name: 'Мадам Ева', eng: 'Madam Eva', slug: 'madam-eva-rhw', type: 'Гуманоид (человек)', cr: '10' },
  { name: 'Мамонт', eng: 'Mammoth', slug: 'mammoth-mm', type: 'Зверь', cr: '6' },
  { name: 'Мантикора', eng: 'Manticore', slug: 'manticore-mm', type: 'Монстр', cr: '3' },
  { name: 'Марид', eng: 'Marid', slug: 'marid-mm', type: 'Элементаль (гений)', cr: '11' },
  { name: 'Марилит', eng: 'Marilith', slug: 'marilith-mm', type: 'Исчадие (демон)', cr: '16' },
  { name: 'Мародёр Таркана', eng: 'Tarkanan Marauder', slug: 'tarkanan-marauder-efa', type: 'Гуманоид', cr: '11' },
  { name: 'Мастифф', eng: 'Mastiff', slug: 'mastiff-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Матушка Лоринда', eng: 'Mother Lorinda', slug: 'mother-lorinda-rhw', type: 'Фея', cr: '8' },
  { name: 'Медик дома Джораско', eng: 'Jorasco Medic', slug: 'jorasco-medic-efa', type: 'Гуманоид (полурослик)', cr: '4' },
  { name: 'Медная горгона', eng: 'Brazen Gorgon', slug: 'brazen-gorgon-mm', type: 'Конструкт', cr: '9' },
  { name: 'Медуза', eng: 'Medusa', slug: 'medusa-mm', type: 'Монстр', cr: '6' },
  { name: 'Меззолот', eng: 'Mezzoloth', slug: 'mezzoloth-mm', type: 'Исчадие (юголот)', cr: '5' },
  { name: 'Мерроу-двуличник', eng: 'Merrow Doublespeaker', slug: 'merrow-doublespeaker-lfl', type: 'Монстр', cr: '4' },
  { name: 'Мерроу-подстрекатель', eng: 'Merrow Haranguer', slug: 'merrow-haranguer-lfl', type: 'Монстр', cr: '5' },
  { name: 'Мёртвая голова', eng: 'Death\'s Head', slug: 'death-s-head-rhw', type: 'Нежить', cr: '1/2' },
  { name: 'Мерфолк волновод', eng: 'Merfolk Wavebender', slug: 'merfolk-wavebender-mm', type: 'Элементаль', cr: '6' },
  { name: 'Мерфолк застрельщик', eng: 'Merfolk Skirmisher', slug: 'merfolk-skirmisher-mm', type: 'Элементаль', cr: '1/8' },
  { name: 'Мерцающий пёс', eng: 'Blink Dog', slug: 'blink-dog-mm', type: 'Фея', cr: '1/4' },
  { name: 'Мечник-заклинатель Черной короны', eng: 'Blackcrown Spellsword', slug: 'blackcrown-spellsword-feq', type: 'Гуманоид (человек)', cr: '1/2' },
  { name: 'Ми-го', eng: 'Mi-Go', slug: 'mi-go-rhw', type: 'Аберрация', cr: '9' },
  { name: 'Мимик', eng: 'Mimic', slug: 'mimic-mm', type: 'Монстр', cr: '2' },
  { name: 'Минотавр Бафомета', eng: 'Minotaur of Baphomet', slug: 'minotaur-of-baphomet-mm', type: 'Монстр', cr: '3' },
  { name: 'Мистический вихрь', eng: 'Eldritch Eddy', slug: 'eldritch-eddy-nf', type: 'Конструкт', cr: '6' },
  { name: 'Младший эмиссар порождения звёзд', eng: 'Lesser Star Spawn Emissary', slug: 'lesser-star-spawn-emissary-rhw', type: 'Аберрация', cr: '19' },
  { name: 'Модрон дуодрон', eng: 'Modron Duodrone', slug: 'modron-duodrone-mm', type: 'Конструкт', cr: '1/4' },
  { name: 'Модрон квадрон', eng: 'Modron Quadrone', slug: 'modron-quadrone-mm', type: 'Конструкт', cr: '1' },
  { name: 'Модрон монодрон', eng: 'Modron Monodrone', slug: 'modron-monodrone-mm', type: 'Конструкт', cr: '1/8' },
  { name: 'Модрон пентадрон', eng: 'Modron Pentadrone', slug: 'modron-pentadrone-mm', type: 'Конструкт', cr: '2' },
  { name: 'Модрон тридрон', eng: 'Modron Tridrone', slug: 'modron-tridrone-mm', type: 'Конструкт', cr: '1/2' },
  { name: 'Мозг в банке', eng: 'Brain in a Jar', slug: 'brain-in-a-jar-rhw', type: 'Нежить', cr: '3' },
  { name: 'Молодой белый дракон', eng: 'Young White Dragon', slug: 'young-white-dragon-mm', type: 'Дракон (цветной)', cr: '6' },
  { name: 'Молодой бронзовый дракон', eng: 'Young Bronze Dragon', slug: 'young-bronze-dragon-mm', type: 'Дракон (металлический)', cr: '8' },
  { name: 'Молодой волшебный дракончик', eng: 'Faerie Dragon Youth', slug: 'faerie-dragon-youth-mm', type: 'Дракон', cr: '1' },
  { name: 'Молодой глубинный дракон', eng: 'Young Deep Dragon', slug: 'young-deep-dragon-fraif', type: 'Дракон', cr: '5' },
  { name: 'Молодой духовный дракон', eng: 'Young Spirit Dragon', slug: 'young-spirit-dragon-fraif', type: 'Дракон', cr: '8' },
  { name: 'Молодой зелёный дракон', eng: 'Young Green Dragon', slug: 'young-green-dragon-mm', type: 'Дракон (цветной)', cr: '8' },
  { name: 'Молодой золотой дракон', eng: 'Young Gold Dragon', slug: 'young-gold-dragon-mm', type: 'Дракон (металлический)', cr: '10' },
  { name: 'Молодой красный дракон', eng: 'Young Red Dragon', slug: 'young-red-dragon-mm', type: 'Дракон (цветной)', cr: '10' },
  { name: 'Молодой латунный дракон', eng: 'Young Brass Dragon', slug: 'young-brass-dragon-mm', type: 'Дракон (металлический)', cr: '6' },
  { name: 'Молодой медный дракон', eng: 'Young Copper Dragon', slug: 'young-copper-dragon-mm', type: 'Дракон (металлический)', cr: '7' },
  { name: 'Молодой ремораз', eng: 'Young Remorhaz', slug: 'young-remorhaz-mm', type: 'Монстр', cr: '5' },
  { name: 'Молодой серебряный дракон', eng: 'Young Silver Dragon', slug: 'young-silver-dragon-mm', type: 'Дракон (металлический)', cr: '9' },
  { name: 'Молодой синий дракон', eng: 'Young Blue Dragon', slug: 'young-blue-dragon-mm', type: 'Дракон (цветной)', cr: '9' },
  { name: 'Молодой теневой дракон', eng: 'Juvenile Shadow Dragon', slug: 'juvenile-shadow-dragon-mm', type: 'Дракон', cr: '4' },
  { name: 'Молодой чёрный дракон', eng: 'Young Black Dragon', slug: 'young-black-dragon-mm', type: 'Дракон (цветной)', cr: '7' },
  { name: 'Монстр Морденхейма', eng: 'Mordenheim\'s Monster', slug: 'mordenheim-s-monster-rhw', type: 'Конструкт', cr: '12' },
  { name: 'Морозный великан', eng: 'Frost Giant', slug: 'frost-giant-mm', type: 'Великан', cr: '8' },
  { name: 'Морская карга', eng: 'Sea Hag', slug: 'sea-hag-mm', type: 'Фея', cr: '2' },
  { name: 'Мул', eng: 'Mule', slug: 'mule-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Мумия', eng: 'Mummy', slug: 'mummy-mm', type: 'Нежить', cr: '3' },
  { name: 'Мэйн', eng: 'Manes', slug: 'manes-mm', type: 'Исчадие (демон)', cr: '1/8' },
  { name: 'Мэншун', eng: 'Manshoon', slug: 'manshoon-fraif', type: 'Гуманоид (человек, волшебник)', cr: '13' },
  { name: 'Мясной голем', eng: 'Flesh Golem', slug: 'flesh-golem-mm', type: 'Конструкт', cr: '5' },
  { name: 'Наблюдатель', eng: 'Spectator', slug: 'spectator-mm', type: 'Аберрация (бехолдер)', cr: '3' },
  { name: 'Нага стражник', eng: 'Guardian Naga', slug: 'guardian-naga-mm', type: 'Небожитель', cr: '10' },
  { name: 'Найтгаунт', eng: 'Nightgaunt', slug: 'nightgaunt-rhw', type: 'Аберрация', cr: '8' },
  { name: 'Налётчик Дааска', eng: 'Daask Raider', slug: 'daask-raider-efa', type: 'Гуманоид (гнолл)', cr: '1' },
  { name: 'Нальфешни', eng: 'Nalfeshnee', slug: 'nalfeshnee-mm', type: 'Исчадие (демон)', cr: '13' },
  { name: 'Наследник Дома Вадалис', eng: 'Vadalis Heir', slug: 'vadalis-heir-efa', type: 'Гуманоид (человек)', cr: '4' },
  { name: 'Наследник Дома Лирандар', eng: 'Lyrandar Scion', slug: 'lyrandar-scion-efa', type: 'Гуманоид (хоравар)', cr: '4' },
  { name: 'Невидимый охотник', eng: 'Invisible Stalker', slug: 'invisible-stalker-mm', type: 'Элементаль', cr: '6' },
  { name: 'Невыразимый ужас', eng: 'Unspeakable Horror', slug: 'unspeakable-horror-rhw', type: 'Монстр', cr: '8' },
  { name: 'Некрихор', eng: 'Necrichor', slug: 'necrichor-rhw', type: 'Нежить', cr: '7' },
  { name: 'Никалот', eng: 'Nycaloth', slug: 'nycaloth-mm', type: 'Исчадие (юголот)', cr: '9' },
  { name: 'Нимблрайт-громила', eng: 'Nimblewright Hulk', slug: 'nimblewright-hulk-fraif', type: 'Конструкт', cr: '7' },
  { name: 'Нимблрайт-скакун', eng: 'Nimblewright Steed', slug: 'nimblewright-steed-fraif', type: 'Конструкт', cr: '2' },
  { name: 'Нимблрайт-страж', eng: 'Nimblewright Guard', slug: 'nimblewright-guard-fraif', type: 'Конструкт', cr: '3' },
  { name: 'Ноггл дикой магии', eng: 'Noggle Wild Mage', slug: 'noggle-wild-mage-lfl', type: 'Фея', cr: '1' },
  { name: 'Ноггл-мародёр', eng: 'Noggle Ransacker', slug: 'noggle-ransacker-lfl', type: 'Фея', cr: '1/4' },
  { name: 'Носорог', eng: 'Rhinoceros', slug: 'rhinoceros-mm', type: 'Зверь', cr: '2' },
  { name: 'Нотик', eng: 'Nothic', slug: 'nothic-mm', type: 'Аберрация', cr: '2' },
  { name: 'Ночная карга', eng: 'Night Hag', slug: 'night-hag-mm', type: 'Исчадие', cr: '5' },
  { name: 'Обезьяна', eng: 'Ape', slug: 'ape-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Облачный великан', eng: 'Cloud Giant', slug: 'cloud-giant-mm', type: 'Великан', cr: '9' },
  { name: 'Оборотень-виверна', eng: 'Werewyvern', slug: 'werewyvern-fraif', type: 'Дракон (оборотень)', cr: '8' },
  { name: 'Огненный великан', eng: 'Fire Giant', slug: 'fire-giant-mm', type: 'Великан', cr: '9' },
  { name: 'Огр', eng: 'Ogre', slug: 'ogre-mm', type: 'Великан', cr: '2' },
  { name: 'Огриллон', eng: 'Ogrillon Ogre', slug: 'ogrillon-ogre-mm', type: 'Великан', cr: '1' },
  { name: 'Одарённый благородный', eng: 'Noble Prodigy', slug: 'noble-prodigy-mm', type: 'Гуманоид', cr: '10' },
  { name: 'Оживлённая метла', eng: 'Animated Broom', slug: 'animated-broom-mm', type: 'Конструкт', cr: '1/4' },
  { name: 'Оживлённый доспех', eng: 'Animated Armor', slug: 'animated-armor-mm', type: 'Конструкт', cr: '1' },
  { name: 'Оживлённый ковёр', eng: 'Animated Rug of Smothering', slug: 'animated-rug-of-smothering-mm', type: 'Конструкт', cr: '2' },
  { name: 'Оживлённый меч', eng: 'Animated Flying Sword', slug: 'animated-flying-sword-mm', type: 'Конструкт', cr: '1/4' },
  { name: 'Окаменяющая мёртвая голова', eng: 'Petrifying Death\'s Head', slug: 'petrifying-death-s-head-rhw', type: 'Нежить', cr: '1' },
  { name: 'Они', eng: 'Oni', slug: 'oni-mm', type: 'Исчадие', cr: '7' },
  { name: 'Орласск', eng: 'Orlassk', slug: 'orlassk-feq', type: 'Аберрация', cr: '23' },
  { name: 'Отвратительный йети', eng: 'Abominable Yeti', slug: 'abominable-yeti-mm', type: 'Монстр', cr: '9' },
  { name: 'Отидж', eng: 'Otyugh', slug: 'otyugh-mm', type: 'Аберрация', cr: '5' },
  { name: 'Отпрыск Троицы мертвых', eng: 'Dead Three Scion', slug: 'dead-three-scion-fraif', type: 'Гуманоид', cr: '16' },
  { name: 'Охотник Дома Тарашк', eng: 'Tharashk Hunter', slug: 'tharashk-hunter-efa', type: 'Гуманоид (человек, орк)', cr: '6' },
  { name: 'Охотничья акула', eng: 'Hunter Shark', slug: 'hunter-shark-mm', type: 'Зверь', cr: '2' },
  { name: 'Падальщик-преследователь', eng: 'Carrion Stalker', slug: 'carrion-stalker-rhw', type: 'Аберрация', cr: '3' },
  { name: 'Пантера', eng: 'Panther', slug: 'panther-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Панцирница', eng: 'Bulette', slug: 'bulette-mm', type: 'Монстр', cr: '5' },
  { name: 'Паровой мефит', eng: 'Steam Mephit', slug: 'steam-mephit-mm', type: 'Элементаль', cr: '1/4' },
  { name: 'Пегас', eng: 'Pegasus', slug: 'pegasus-mm', type: 'Небожитель', cr: '2' },
  { name: 'Первобытный совомед', eng: 'Primeval Owlbear', slug: 'primeval-owlbear-mm', type: 'Монстр', cr: '7' },
  { name: 'Перитон', eng: 'Peryton', slug: 'peryton-mm', type: 'Монстр', cr: '2' },
  { name: 'Пёс смерти', eng: 'Death Dog', slug: 'death-dog-mm', type: 'Монстр', cr: '1' },
  { name: 'Пикси', eng: 'Pixie', slug: 'pixie-mm', type: 'Фея', cr: '1/4' },
  { name: 'Пикси чудотворец', eng: 'Pixie Wonderbringer', slug: 'pixie-wonderbringer-mm', type: 'Фея', cr: '5' },
  { name: 'Пират', eng: 'Pirate', slug: 'pirate-mm', type: 'Гуманоид', cr: '1' },
  { name: 'Пират адмирал', eng: 'Pirate Admiral', slug: 'pirate-admiral-mm', type: 'Гуманоид', cr: '12' },
  { name: 'Пират капитан', eng: 'Pirate Captain', slug: 'pirate-captain-mm', type: 'Гуманоид', cr: '6' },
  { name: 'Писец Дома Сивис', eng: 'Sivis Scribe', slug: 'sivis-scribe-efa', type: 'Гуманоид (гном)', cr: '3' },
  { name: 'Планетар', eng: 'Planetar', slug: 'planetar-mm', type: 'Небожитель (ангел)', cr: '16' },
  { name: 'Плащевик', eng: 'Cloaker', slug: 'cloaker-mm', type: 'Аберрация', cr: '8' },
  { name: 'Плезиозавр', eng: 'Plesiosaurus', slug: 'plesiosaurus-mm', type: 'Зверь (динозавр)', cr: '2' },
  { name: 'Подручный Боромаров', eng: 'Boromar Underboss', slug: 'boromar-underboss-efa', type: 'Гуманоид (полурослик)', cr: '8' },
  { name: 'Пожиратель интеллекта', eng: 'Intellect Devourer', slug: 'intellect-devourer-mm', type: 'Аберрация', cr: '2' },
  { name: 'Ползающая насыпь', eng: 'Shambling Mound', slug: 'shambling-mound-mm', type: 'Растение', cr: '5' },
  { name: 'Ползающая рука', eng: 'Crawling Claw', slug: 'crawling-claw-mm', type: 'Нежить', cr: '0' },
  { name: 'Ползающий падальщик', eng: 'Carrion Crawler', slug: 'carrion-crawler-mm', type: 'Монстр', cr: '2' },
  { name: 'Полтергейст', eng: 'Poltergeist', slug: 'poltergeist-mm', type: 'Нежить', cr: '2' },
  { name: 'Полудракон', eng: 'Half-Dragon', slug: 'half-dragon-mm', type: 'Дракон', cr: '5' },
  { name: 'Полярный змей', eng: 'Polar Serpent', slug: 'polar-serpent-fraif', type: 'Элементаль', cr: '3' },
  { name: 'Пони', eng: 'Pony', slug: 'pony-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Порождение вампира', eng: 'Vampire Spawn', slug: 'vampire-spawn-mm', type: 'Нежить', cr: '5' },
  { name: 'Привидение', eng: 'Ghost', slug: 'ghost-mm', type: 'Нежить', cr: '4' },
  { name: 'Призрак', eng: 'Wraith', slug: 'wraith-mm', type: 'Нежить', cr: '5' },
  { name: 'Пробуждённое дерево', eng: 'Awakened Tree', slug: 'awakened-tree-mm', type: 'Растение', cr: '2' },
  { name: 'Пробуждённый куст', eng: 'Awakened Shrub', slug: 'awakened-shrub-mm', type: 'Растение', cr: '0' },
  { name: 'Прожорливый рой насекомых', eng: 'Swarm of Ravenous Insects', slug: 'swarm-of-ravenous-insects-rhw', type: 'Рой крошечных зверей', cr: '3' },
  { name: 'Пронзатель', eng: 'Piercer', slug: 'piercer-mm', type: 'Аберрация', cr: '1/2' },
  { name: 'Псевдодракон', eng: 'Pseudodragon', slug: 'pseudodragon-mm', type: 'Дракон', cr: '1/4' },
  { name: 'Психическая серая слизь', eng: 'Psychic Gray Ooze', slug: 'psychic-gray-ooze-mm', type: 'Слизь', cr: '1' },
  { name: 'Птеранодон', eng: 'Pteranodon', slug: 'pteranodon-mm', type: 'Зверь (динозавр)', cr: '1/4' },
  { name: 'Пугало', eng: 'Scarecrow', slug: 'scarecrow-mm', type: 'Конструкт', cr: '1' },
  { name: 'Пурпурный червь', eng: 'Purple Worm', slug: 'purple-worm-mm', type: 'Монстр', cr: '15' },
  { name: 'Пылающий скелет', eng: 'Flaming Skeleton', slug: 'flaming-skeleton-mm', type: 'Нежить', cr: '3' },
  { name: 'Пылающий череп', eng: 'Flameskull', slug: 'flameskull-mm', type: 'Нежить', cr: '4' },
  { name: 'Пылевой мефит', eng: 'Dust Mephit', slug: 'dust-mephit-mm', type: 'Элементаль', cr: '1/2' },
  { name: 'Разведчик', eng: 'Scout', slug: 'scout-mm', type: 'Гуманоид', cr: '1/2' },
  { name: 'Разведчик капитан', eng: 'Scout Captain', slug: 'scout-captain-mm', type: 'Гуманоид', cr: '3' },
  { name: 'Ракшаса', eng: 'Rakshasa', slug: 'rakshasa-mm', type: 'Исчадие', cr: '13' },
  { name: 'Рамья Васавадан', eng: 'Ramya Vasavadan', slug: 'ramya-vasavadan-rhw', type: 'Нежить', cr: '15' },
  { name: 'Растение-похититель тел', eng: 'Bodytaker Plant', slug: 'bodytaker-plant-rhw', type: 'Растение', cr: '7' },
  { name: 'Ревенант', eng: 'Revenant', slug: 'revenant-mm', type: 'Нежить', cr: '5' },
  { name: 'Ревенант кладбище', eng: 'Graveyard Revenant', slug: 'graveyard-revenant-mm', type: 'Нежить', cr: '7' },
  { name: 'Ревенант-обитель', eng: 'Haunting Revenant', slug: 'haunting-revenant-mm', type: 'Нежить', cr: '10' },
  { name: 'Ремораз', eng: 'Remorhaz', slug: 'remorhaz-mm', type: 'Монстр', cr: '11' },
  { name: 'Решала дома Гхалланда', eng: 'Ghallanda Troubleshooter', slug: 'ghallanda-troubleshooter-efa', type: 'Гуманоид (полурослик)', cr: '3' },
  { name: 'Ржавник', eng: 'Rust Monster', slug: 'rust-monster-mm', type: 'Монстр', cr: '1/2' },
  { name: 'Ржавый берсеркер', eng: 'Rusted Berserker', slug: 'rusted-berserker-fraif', type: 'Конструкт', cr: '4' },
  { name: 'Ржавый змей', eng: 'Rusted Wyrm', slug: 'rusted-wyrm-fraif', type: 'Конструкт', cr: '14' },
  { name: 'Ржавый исполин', eng: 'Rusted Behemoth', slug: 'rusted-behemoth-fraif', type: 'Конструкт', cr: '9' },
  { name: 'Рифовая акула', eng: 'Reef Shark', slug: 'reef-shark-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Рогатый дьявол', eng: 'Horned Devil', slug: 'horned-devil-mm', type: 'Исчадие (дьявол)', cr: '11' },
  { name: 'Рой воронов', eng: 'Swarm of Ravens', slug: 'swarm-of-ravens-mm', type: 'Рой крошечных зверей', cr: '1/4' },
  { name: 'Рой дретчей', eng: 'Swarm of Dretches', slug: 'swarm-of-dretches-mm', type: 'Рой маленьких исчадий (демон)', cr: '4' },
  { name: 'Рой конечностей зомби', eng: 'Swarm of Zombie Limbs', slug: 'swarm-of-zombie-limbs-rhw', type: 'Рой крошечной нежити', cr: '1' },
  { name: 'Рой кровопийц', eng: 'Swarm of Stirges', slug: 'swarm-of-stirges-mm', type: 'Рой крошечных монстров', cr: '2' },
  { name: 'Рой крыс', eng: 'Swarm of Rats', slug: 'swarm-of-rats-mm', type: 'Рой крошечных зверей', cr: '1/4' },
  { name: 'Рой ларв', eng: 'Swarm of Larvae', slug: 'swarm-of-larvae-mm', type: 'Рой средних исчадий', cr: '1' },
  { name: 'Рой лемуров', eng: 'Swarm of Lemures', slug: 'swarm-of-lemures-mm', type: 'Рой средних исчадий (дьявол)', cr: '3' },
  { name: 'Рой летучих мышей', eng: 'Swarm of Bats', slug: 'swarm-of-bats-mm', type: 'Рой крошечных зверей', cr: '1/4' },
  { name: 'Рой насекомых', eng: 'Swarm of Insects', slug: 'swarm-of-insects-mm', type: 'Рой крошечных зверей', cr: '1/2' },
  { name: 'Рой паразитирующих насекомых', eng: 'Swarm of Infesting Insects', slug: 'swarm-of-infesting-insects-rhw', type: 'Рой крошечных зверей', cr: '2' },
  { name: 'Рой пираний', eng: 'Swarm of Piranhas', slug: 'swarm-of-piranhas-mm', type: 'Рой крошечных зверей', cr: '1' },
  { name: 'Рой ползающих рук', eng: 'Swarm of Crawling Claws', slug: 'swarm-of-crawling-claws-mm', type: 'Рой крошечной нежити', cr: '3' },
  { name: 'Рой ядовитых змей', eng: 'Swarm of Venomous Snakes', slug: 'swarm-of-venomous-snakes-mm', type: 'Рой крошечных зверей', cr: '2' },
  { name: 'Росток миконида', eng: 'Myconid Sprout', slug: 'myconid-sprout-mm', type: 'Растение', cr: '0' },
  { name: 'Рудольф ван Рихтен', eng: 'Rudolph van Richten', slug: 'rudolph-van-richten-rhw', type: 'Гуманоид (человек)', cr: '5' },
  { name: 'Рух', eng: 'Roc', slug: 'roc-mm', type: 'Монстр', cr: '11' },
  { name: 'Рыцарь', eng: 'Knight', slug: 'knight-mm', type: 'Гуманоид', cr: '3' },
  { name: 'Рыцарь Ордена Изумрудного Когтя', eng: 'Emerald Claw Knight', slug: 'emerald-claw-knight-efa', type: 'Гуманоид', cr: '2' },
  { name: 'Рыцарь смерти', eng: 'Death Knight', slug: 'death-knight-mm', type: 'Нежить', cr: '17' },
  { name: 'Рыцарь смерти претендент', eng: 'Death Knight Aspirant', slug: 'death-knight-aspirant-mm', type: 'Нежить', cr: '11' },
  { name: 'Саблезубый тигр', eng: 'Saber-Toothed Tiger', slug: 'saber-toothed-tiger-mm', type: 'Зверь', cr: '2' },
  { name: 'Саламандра', eng: 'Salamander', slug: 'salamander-mm', type: 'Элементаль', cr: '5' },
  { name: 'Саламандра мастер инферно', eng: 'Salamander Inferno Master', slug: 'salamander-inferno-master-mm', type: 'Элементаль', cr: '15' },
  { name: 'Саламандра огненная змея', eng: 'Salamander Fire Snake', slug: 'salamander-fire-snake-mm', type: 'Элементаль', cr: '1' },
  { name: 'Саммастер (форма драколича)', eng: 'Sammaster (Dracolich Form)', slug: 'sammaster-dracolich-form-fraif', type: 'Нежить', cr: '22' },
  { name: 'Саммастер (форма лича)', eng: 'Sammaster (Lich Form)', slug: 'sammaster-lich-form-fraif', type: 'Нежить (волшебник)', cr: '22' },
  { name: 'Сатир', eng: 'Satyr', slug: 'satyr-mm', type: 'Фея', cr: '1/2' },
  { name: 'Сатир мастер кутежа', eng: 'Satyr Revelmaster', slug: 'satyr-revelmaster-mm', type: 'Фея', cr: '6' },
  { name: 'Сахуагин барон', eng: 'Sahuagin Baron', slug: 'sahuagin-baron-mm', type: 'Исчадие', cr: '5' },
  { name: 'Сахуагин воин', eng: 'Sahuagin Warrior', slug: 'sahuagin-warrior-mm', type: 'Исчадие', cr: '1/2' },
  { name: 'Сахуагин жрец', eng: 'Sahuagin Priest', slug: 'sahuagin-priest-mm', type: 'Исчадие', cr: '2' },
  { name: 'Священник', eng: 'Priest', slug: 'priest-mm', type: 'Гуманоид (жрец)', cr: '2' },
  { name: 'Священник послушник', eng: 'Priest Acolyte', slug: 'priest-acolyte-mm', type: 'Гуманоид (жрец)', cr: '1/4' },
  { name: 'Сейдра д\'Онер', eng: 'Saidra d\'Honaire', slug: 'saidra-d-honaire-rhw', type: 'Нежить', cr: '9' },
  { name: 'Серая слизь', eng: 'Gray Ooze', slug: 'gray-ooze-mm', type: 'Слизь', cr: '1/2' },
  { name: 'Серый слаад', eng: 'Gray Slaad', slug: 'gray-slaad-mm', type: 'Аберрация', cr: '9' },
  { name: 'Синий слаад', eng: 'Blue Slaad', slug: 'blue-slaad-mm', type: 'Аберрация', cr: '7' },
  { name: 'Скелет', eng: 'Skeleton', slug: 'skeleton-mm', type: 'Нежить', cr: '1/4' },
  { name: 'Скелет боевого коня', eng: 'Warhorse Skeleton', slug: 'warhorse-skeleton-mm', type: 'Нежить', cr: '1/2' },
  { name: 'Скелет минотавра', eng: 'Minotaur Skeleton', slug: 'minotaur-skeleton-mm', type: 'Нежить', cr: '2' },
  { name: 'Скелет Страда', eng: 'Strahd Skeleton', slug: 'strahd-skeleton-rhw', type: 'Нежить', cr: '4' },
  { name: 'Скиталец Туманов', eng: 'Mist Wanderer', slug: 'mist-wanderer-rhw', type: 'Гуманоид', cr: '3' },
  { name: 'Скорпион', eng: 'Scorpion', slug: 'scorpion-mm', type: 'Зверь', cr: '0' },
  { name: 'Слаад головастик', eng: 'Slaad Tadpole', slug: 'slaad-tadpole-mm', type: 'Аберрация', cr: '1/8' },
  { name: 'Слаад смерти', eng: 'Death Slaad', slug: 'death-slaad-mm', type: 'Аберрация', cr: '10' },
  { name: 'Слон', eng: 'Elephant', slug: 'elephant-mm', type: 'Зверь', cr: '4' },
  { name: 'Сова', eng: 'Owl', slug: 'owl-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Совомед', eng: 'Owlbear', slug: 'owlbear-mm', type: 'Монстр', cr: '3' },
  { name: 'Солар', eng: 'Solar', slug: 'solar-mm', type: 'Небожитель (ангел)', cr: '21' },
  { name: 'Спектр', eng: 'Specter', slug: 'specter-mm', type: 'Нежить', cr: '1' },
  { name: 'Спора Моандера', eng: 'Spore of Moander', slug: 'spore-of-moander-fraif', type: 'Растение', cr: '12' },
  { name: 'Споровой слуга миконидов', eng: 'Myconid Spore Servant', slug: 'myconid-spore-servant-mm', type: 'Растение', cr: '1' },
  { name: 'Спрайт', eng: 'Sprite', slug: 'sprite-mm', type: 'Фея', cr: '1/4' },
  { name: 'Стихийный катаклизм', eng: 'Elemental Cataclysm', slug: 'elemental-cataclysm-mm', type: 'Элементаль (титан)', cr: '22' },
  { name: 'Страд фон Зарович', eng: 'Strahd von Zarovich', slug: 'strahd-von-zarovich-rhw', type: 'Нежить (вампир)', cr: '15' },
  { name: 'Страж Кундарака', eng: 'Kundarak Warden', slug: 'kundarak-warden-efa', type: 'Гуманоид (дварф)', cr: '5' },
  { name: 'Страж-маршал', eng: 'Sentinel Marshal', slug: 'sentinel-marshal-efa', type: 'Гуманоид (человек)', cr: '6' },
  { name: 'Стражник', eng: 'Guard', slug: 'guard-mm', type: 'Гуманоид', cr: '1/8' },
  { name: 'Стражник капитан', eng: 'Guard Captain', slug: 'guard-captain-mm', type: 'Гуманоид', cr: '4' },
  { name: 'Странствующий рыцарь', eng: 'Questing Knight', slug: 'questing-knight-mm', type: 'Гуманоид', cr: '12' },
  { name: 'Стригой', eng: 'Strigoi', slug: 'strigoi-rhw', type: 'Монстр', cr: '4' },
  { name: 'Стручок-двойник похитителя тел', eng: 'Bodytaker Podling', slug: 'bodytaker-podling-rhw', type: 'Растение', cr: '1/2' },
  { name: 'Суккуб', eng: 'Succubus', slug: 'succubus-mm', type: 'Исчадие', cr: '4' },
  { name: 'Сфинкс доблести', eng: 'Sphinx of Valor', slug: 'sphinx-of-valor-mm', type: 'Небожитель', cr: '17' },
  { name: 'Сфинкс знаний', eng: 'Sphinx of Lore', slug: 'sphinx-of-lore-mm', type: 'Небожитель', cr: '11' },
  { name: 'Сфинкс тайн', eng: 'Sphinx of Secrets', slug: 'sphinx-of-secrets-mm', type: 'Небожитель', cr: '8' },
  { name: 'Сфинкс чудес', eng: 'Sphinx of Wonder', slug: 'sphinx-of-wonder-mm', type: 'Небожитель', cr: '1' },
  { name: 'Сыщик Дома Медани', eng: 'Medani Inquisitive', slug: 'medani-inquisitive-efa', type: 'Гуманоид (хоравар)', cr: '3' },
  { name: 'Тарраск', eng: 'Tarrasque', slug: 'tarrasque-mm', type: 'Монстр (титан)', cr: '30' },
  { name: 'Тёмная мантия', eng: 'Darkmantle', slug: 'darkmantle-mm', type: 'Аберрация', cr: '1/2' },
  { name: 'Теневой демон', eng: 'Shadow Demon', slug: 'shadow-demon-mm', type: 'Исчадие (демон)', cr: '4' },
  { name: 'Теневой дракон', eng: 'Shadow Dragon', slug: 'shadow-dragon-mm', type: 'Дракон', cr: '13' },
  { name: 'Теневой странник умбрагенов', eng: 'Umbragen Shadow Walker', slug: 'umbragen-shadow-walker-efa', type: 'Гуманоид (эльф)', cr: '9' },
  { name: 'Тень', eng: 'Shadow', slug: 'shadow-mm', type: 'Нежить', cr: '1/2' },
  { name: 'Тигр', eng: 'Tiger', slug: 'tiger-mm', type: 'Зверь', cr: '1' },
  { name: 'Тиран смерти', eng: 'Death Tyrant', slug: 'death-tyrant-mm', type: 'Нежить (бехолдер)', cr: '14' },
  { name: 'Тираннозавр Рекс', eng: 'Tyrannosaurus Rex', slug: 'tyrannosaurus-rex-mm', type: 'Зверь (динозавр)', cr: '8' },
  { name: 'Топороклюв', eng: 'Axe Beak', slug: 'axe-beak-mm', type: 'Монстр', cr: '1/4' },
  { name: 'Торговец Туманного Рая', eng: 'Merchant of Misthaven', slug: 'merchant-of-misthaven-feq', type: 'Фея', cr: '20' },
  { name: 'Тошнотворный мэйн', eng: 'Manes Vaporspawn', slug: 'manes-vaporspawn-mm', type: 'Исчадие (демон)', cr: '1' },
  { name: 'Трент', eng: 'Treant', slug: 'treant-mm', type: 'Растение', cr: '9' },
  { name: 'Три-крин мародёр', eng: 'Thri-kreen Marauder', slug: 'thri-kreen-marauder-mm', type: 'Монстр', cr: '1' },
  { name: 'Три-крин псионик', eng: 'Thri-kreen Psion', slug: 'thri-kreen-psion-mm', type: 'Монстр', cr: '8' },
  { name: 'Трицератопс', eng: 'Triceratops', slug: 'triceratops-mm', type: 'Зверь (динозавр)', cr: '5' },
  { name: 'Троглодит', eng: 'Troglodyte', slug: 'troglodyte-mm', type: 'Монстр', cr: '1/4' },
  { name: 'Тролль', eng: 'Troll', slug: 'troll-mm', type: 'Великан', cr: '5' },
  { name: 'Трупонетка', eng: 'Carrionette', slug: 'carrionette-rhw', type: 'Конструкт', cr: '1' },
  { name: 'Убийца Вулкоора', eng: 'Vulkoori Stingblade', slug: 'vulkoori-stingblade-efa', type: 'Гуманоид (эльф)', cr: '1/2' },
  { name: 'Удав', eng: 'Constrictor Snake', slug: 'constrictor-snake-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Ужас Туманов', eng: 'Mist Horror', slug: 'mist-horror-rhw', type: 'Нежить', cr: '3' },
  { name: 'Уилфред Годфруа', eng: 'Wilfred Godefroy', slug: 'wilfred-godefroy-rhw', type: 'Нежить', cr: '6' },
  { name: 'Ультролот', eng: 'Ultroloth', slug: 'ultroloth-mm', type: 'Исчадие (юголот)', cr: '13' },
  { name: 'Умертвие', eng: 'Wight', slug: 'wight-mm', type: 'Нежить', cr: '3' },
  { name: 'Упряжная лошадь', eng: 'Draft Horse', slug: 'draft-horse-mm', type: 'Зверь', cr: '1/4' },
  { name: 'Упырь', eng: 'Ghoul', slug: 'ghoul-mm', type: 'Нежить', cr: '1' },
  { name: 'Упырь утопец', eng: 'Lacedon Ghoul', slug: 'lacedon-ghoul-mm', type: 'Нежить', cr: '1' },
  { name: 'Ускользающий зверь', eng: 'Displacer Beast', slug: 'displacer-beast-mm', type: 'Монстр', cr: '3' },
  { name: 'Фазовый паук', eng: 'Phase Spider', slug: 'phase-spider-mm', type: 'Монстр', cr: '3' },
  { name: 'Фамильяр вампира', eng: 'Vampire Familiar', slug: 'vampire-familiar-mm', type: 'Гуманоид', cr: '3' },
  { name: 'Фаэримм детёныш ', eng: 'Phaerimm Hatchling', slug: 'phaerimm-hatchling-fraif', type: 'Аберрация', cr: '1/4' },
  { name: 'Фаэримм-разведчик', eng: 'Phaerimm Scout', slug: 'phaerimm-scout-nf', type: 'Аберрация', cr: '2' },
  { name: 'Фламф', eng: 'Flumph', slug: 'flumph-mm', type: 'Аберрация', cr: '1/8' },
  { name: 'Фомор', eng: 'Fomorian', slug: 'fomorian-mm', type: 'Великан', cr: '8' },
  { name: 'Хазлик', eng: 'Hazlik', slug: 'hazlik-rhw', type: 'Гуманоид (человек, волшебник)', cr: '14' },
  { name: 'Харкон Лукас', eng: 'Harkon Lukas', slug: 'harkon-lukas-rhw', type: 'Монстр (оборотень)', cr: '14' },
  { name: 'Хезроу', eng: 'Hezrou', slug: 'hezrou-mm', type: 'Исчадие (демон)', cr: '8' },
  { name: 'Химера', eng: 'Chimera', slug: 'chimera-mm', type: 'Монстр', cr: '6' },
  { name: 'Хобгоблин воин', eng: 'Hobgoblin Warrior', slug: 'hobgoblin-warrior-mm', type: 'Фея (гоблиноид)', cr: '1/2' },
  { name: 'Хобгоблин капитан', eng: 'Hobgoblin Captain', slug: 'hobgoblin-captain-mm', type: 'Фея (гоблиноид)', cr: '3' },
  { name: 'Хобгоблин полководец', eng: 'Hobgoblin Warlord', slug: 'hobgoblin-warlord-mm', type: 'Фея (гоблиноид)', cr: '6' },
  { name: 'Холмовой великан', eng: 'Hill Giant', slug: 'hill-giant-mm', type: 'Великан', cr: '5' },
  { name: 'Цзянши', eng: 'Jiangshi', slug: 'jiangshi-rhw', type: 'Нежить', cr: '9' },
  { name: 'Циклоп оракул', eng: 'Cyclops Oracle', slug: 'cyclops-oracle-mm', type: 'Великан', cr: '10' },
  { name: 'Циклоп часовой', eng: 'Cyclops Sentry', slug: 'cyclops-sentry-mm', type: 'Великан', cr: '6' },
  { name: 'Чазм', eng: 'Chasme', slug: 'chasme-mm', type: 'Исчадие (демон)', cr: '6' },
  { name: 'Чакуна', eng: 'Chakuna', slug: 'chakuna-rhw', type: 'Монстр', cr: '11' },
  { name: 'Чёрная слизь', eng: 'Black Pudding', slug: 'black-pudding-mm', type: 'Слизь', cr: '4' },
  { name: 'Чёрный медведь', eng: 'Black Bear', slug: 'black-bear-mm', type: 'Зверь', cr: '1/2' },
  { name: 'Чуул', eng: 'Chuul', slug: 'chuul-mm', type: 'Аберрация', cr: '4' },
  { name: 'Шакал', eng: 'Jackal', slug: 'jackal-mm', type: 'Зверь', cr: '0' },
  { name: 'Шакалвер', eng: 'Jackalwere', slug: 'jackalwere-mm', type: 'Исчадие', cr: '1/2' },
  { name: 'Шипастый дьявол', eng: 'Barbed Devil', slug: 'barbed-devil-mm', type: 'Исчадие (дьявол)', cr: '5' },
  { name: 'Шлемоносный ужас', eng: 'Helmed Horror', slug: 'helmed-horror-mm', type: 'Конструкт', cr: '4' },
  { name: 'Шоггот', eng: 'Shoggoth', slug: 'shoggoth-rhw', type: 'Аберрация', cr: '11' },
  { name: 'Шпион', eng: 'Spy', slug: 'spy-mm', type: 'Гуманоид', cr: '1' },
  { name: 'Шпион мастер', eng: 'Spy Master', slug: 'spy-master-mm', type: 'Гуманоид', cr: '10' },
  { name: 'Штормовой великан', eng: 'Storm Giant', slug: 'storm-giant-mm', type: 'Великан', cr: '13' },
  { name: 'Щенок панцирницы', eng: 'Bulette Pup', slug: 'bulette-pup-mm', type: 'Монстр', cr: '2' },
  { name: 'Щитостраж', eng: 'Shield Guardian', slug: 'shield-guardian-mm', type: 'Конструкт', cr: '7' },
  { name: 'Эбонбейн', eng: 'Ebonbane', slug: 'ebonbane-rhw', type: 'Конструкт', cr: '13' },
  { name: 'Эз д\'Авенир', eng: 'Ez d\'Avenir', slug: 'ez-d-avenir-rhw', type: 'Гуманоид (человек)', cr: '8' },
  { name: 'Эйзер защитник', eng: 'Azer Sentinel', slug: 'azer-sentinel-mm', type: 'Элементаль', cr: '2' },
  { name: 'Эйзер пиромант', eng: 'Azer Pyromancer', slug: 'azer-pyromancer-mm', type: 'Элементаль', cr: '6' },
  { name: 'Элементаль воды', eng: 'Water Elemental', slug: 'water-elemental-mm', type: 'Элементаль', cr: '5' },
  { name: 'Элементаль воздуха', eng: 'Air Elemental', slug: 'air-elemental-mm', type: 'Элементаль', cr: '5' },
  { name: 'Элементаль земли', eng: 'Earth Elemental', slug: 'earth-elemental-mm', type: 'Элементаль', cr: '5' },
  { name: 'Элементаль огня', eng: 'Fire Elemental', slug: 'fire-elemental-mm', type: 'Элементаль', cr: '5' },
  { name: 'Эмпирей', eng: 'Empyrean', slug: 'empyrean-mm', type: 'Небожитель, Исчадие (титан)', cr: '23' },
  { name: 'Эмпирей йота', eng: 'Empyrean Iota', slug: 'empyrean-iota-mm', type: 'Небожитель, Исчадие (титан)', cr: '1' },
  { name: 'Эриния', eng: 'Erinyes', slug: 'erinyes-mm', type: 'Исчадие (дьявол)', cr: '12' },
  { name: 'Эттеркап', eng: 'Ettercap', slug: 'ettercap-mm', type: 'Монстр', cr: '2' },
  { name: 'Эттин', eng: 'Ettin', slug: 'ettin-mm', type: 'Великан', cr: '4' },
  { name: 'Юань-ти абоминация', eng: 'Yuan-ti Abomination', slug: 'yuan-ti-abomination-mm', type: 'Монстр', cr: '7' },
  { name: 'Юань-ти лазутчик', eng: 'Yuan-ti Infiltrator', slug: 'yuan-ti-infiltrator-mm', type: 'Монстр', cr: '1' },
  { name: 'Юань-ти проклинатель (тип 1)', eng: 'Yuan-ti Malison (Type 1)', slug: 'yuan-ti-malison-type-1-mm', type: 'Монстр', cr: '3' },
  { name: 'Юань-ти проклинатель (тип 2)', eng: 'Yuan-ti Malison (Type 2)', slug: 'yuan-ti-malison-type-2-mm', type: 'Монстр', cr: '3' },
  { name: 'Юань-ти проклинатель (тип 3)', eng: 'Yuan-ti Malison (Type 3)', slug: 'yuan-ti-malison-type-3-mm', type: 'Монстр', cr: '3' },
  { name: 'Ядовитая змея', eng: 'Venomous Snake', slug: 'venomous-snake-mm', type: 'Зверь', cr: '1/8' },
  { name: 'Ястреб', eng: 'Hawk', slug: 'hawk-mm', type: 'Зверь', cr: '0' },
  { name: 'Ящерица', eng: 'Lizard', slug: 'lizard-mm', type: 'Зверь', cr: '0' },
];
